### ISSUE TITLE
DTMF not execute action defined

### ISSUE THREAD

**Issue by julienabbe** [motom001/DoorPi#102]
Hi.
First time I install DoorPi.
Installation's fine, configuration seems too.

DoorPi initiates a call when a button is push (GPIO) according my doorpi.cfg
I've a relay board on GPIO, functionning, direct access to GPIO effectively switch it.
But configured DTMF ( "#" = out:opendoor,1,0,2) doesn't respond, nothing in log, even in trace, DTMF seems not to be catched.

DoorPi is registered on French operator named "Free", calling a mobile phone.

Best regards

**Comment by Schwa-l-be** [comment]
If theres nothing logged or an error mesage, it seemes like your operator doesn't support DTMF and the problem is not part of doorpi. Do you have any chance to try doorpi on an other SIP Provider or a local server?
You can also upload your config probabliy there is an mistake.

**Comment by julienabbe** [comment]
Is the DTMF mode (rcf2833 or inband) set somewhere in a config file ?

**Comment by Schwa-l-be** [comment]
I'm not sure which DTMF mode is used, as i know there is no possibility to set the mode in config. Maybe @motom001 could answer this question.

**Comment by julienabbe** [comment]
I've just look as this.

Linphone API for DTMF setting is available :
http://pythonhosted.org/linphone/api_reference.html?highlight=dtmf#linphone.Core.use_info_for_dtmf
http://pythonhosted.org/linphone/api_reference.html?highlight=dtmf#linphone.Core.use_rfc2833_for_dtmf

Maybe add a new parameter in from_linphone.py ?

I will do some tests an post results soon.

**Comment by julienabbe** [comment]
The behaviour isn't the one I expected.
Set default to True to each properties won't works....
Parameters are well passed to properties, but linphone returns a bad result.

15-08-31 20:48:30,695 [TRACE]  	[conf.config_object] get_boolean for key use_info_for_dtmf in section SIP-Phone (default: True) returns True
2015-08-31 20:48:30,699 [DEBUG]  	[sipphone.from_linphone] 	[PYLINPHONE] >>> pylinphone_Core_set_use_info_for_dtmf(0xb4b06878 [0x1d77600], 0x27c6a0 [1])
2015-08-31 20:48:30,705 [DEBUG]  	[sipphone.from_linphone] 	[PYLINPHONE] <<< pylinphone_Core_set_use_info_for_dtmf -> 0
2015-08-31 20:48:30,710 [TRACE]  	[conf.config_object] get_boolean for key use_rfc2833_for_dtmf in section SIP-Phone (default: True) returns True
2015-08-31 20:48:30,714 [DEBUG]  	[sipphone.from_linphone] 	[PYLINPHONE] >>> pylinphone_Core_set_use_rfc2833_for_dtmf(0xb4b06878 [0x1d77600], 0x27c6a0 [1])
2015-08-31 20:48:30,719 [DEBUG]  	[sipphone.from_linphone] 	[PYLINPHONE] <<< pylinphone_Core_set_use_rfc2833_for_dtmf -> 0    

Still investigating...

**Comment by motom001** [comment]
And only set one of this to true?
What says linphone, when you set it to false?
Which version of linphone do you use?

**Comment by julienabbe** [comment]
if only one sets, same return.
If set to False, the result from Linphone is False

Using linphone4raspberry-3.8.2_89_g8415d54-cp27-none-any.whl

Line 228 in from_linphone.py

        self.core.use_rfc2833_for_dtmf = conf.get_bool(SIPPHONE_SECTION, 'use_rfc2833_for_dtmf', True)
        self.core.use_info_for_dtmf = conf.get_bool(SIPPHONE_SECTION, 'use_info_for_dtmf', True)

**Comment by motom001** [comment]
I think @Schwa-l-be is rigth with this:
"it seemes like your operator doesn't support DTMF and the problem is not part of doorpi."
It's a problem of DTMF from your mobile phone to doorpi, isn't it?
So please try it with another device wich doen't communicate over the same SIP-Server (maybe from your computer by using linphone client) and tell us if the problem still exists.

**Comment by julienabbe** [comment]
Using local asterisk, everything's fine.
First time I have DTMF issue with my operator...
