### ISSUE TITLE
Fehler bei History Snapshot, wenn keine Bidler vorhanden sind

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#103]
Hab per Mail die Info bekommen, dass es zu einer Exception kommt, wenn keine Bilder vorhanden sind und die Weboberfläche aufgerufen wird.

![mc root raspberrypi varlogdoorpi - shell in a box - google chrome_2015-09-02_10-52-18](https://cloud.githubusercontent.com/assets/9497035/9654047/33220e9a-5228-11e5-8cf1-ff91809a171d.png)

**Comment by motom001** [comment]
@pistreamer - Kannst Du das bitte übernehmen?

**Comment by pistreamer** [comment]
hallo ja schaue ich mir gleich an thx !

**Comment by motom001** [comment]
WOW - danke für die schnelle Hilfe...

Löst das wirklich das Problem oder müsste files anders vorbelegt werden? z.B. mit `files = dict`oder ähnliches? Ich weiß nicht was an den Webclient zurückgegeben wird /  werden soll...

**Comment by pistreamer** [comment]
War sowieso gerade im Code unterwegs zwecks Linphone. (Übertragungsprobleme Audio/Video mit Asterisks VP8 patch am Raspberry PI ;-) . Im Prinzip schon, aber html seitig habe ich, dann einen Fehler, da es die Länge nicht gibt und wenn das dict leer bekomme ich auch einen Fehler in der Console. 
Nachdem du ohnehin gemeint hast ich sollte das html überarbeiten werde ich, dass gleich miteinpflegen.

**Comment by pistreamer** [comment]
Habe nun das html File angepasst und würde es gerne einchecken. Wie siehts mit den Berechtigungen aus sonst lade ich die Änderungen bei meinem Trunk hoch?
