### ISSUE TITLE
Mikro an der Aussenstation

### ISSUE THREAD

**Issue by ghost** [motom001/DoorPi#104]
Hallo,
ich habe bemerkt dass das Mikro an der Aussenstation bei einem Anruf an die Aussenstation nicht geht.
So jetzt nochmal ausführlicher ;-)
DoorPI hat bei mir intern die SIP Nummer 620 die Clients 621 - 624. Wenn ich nun von irgendeinem client anrufe wird der Anruf durchgestellt und der Lautsprecher an der Aussenstation übertragt das was ich in das Mikro des client spreche. Spreche ich nun in das Mikro an der Aussenstation kommt hier nichts bei dem client an.
Anders herum wenn die Aussenstation einen client anruft funktioniert alles sehr gut.
Ist das so gewollt oder ein bug?

**Comment by pistreamer** [comment]
Hallo Schnillo, wollte deinen Fehler gerade reproduzieren. Habe die neueste doorpi Version von github mittels neuen setup Script installiert. Bei mir funktionierte zunächst das Mikrofon bei doorpi auch nicht, da ich beim Client (Linphone am Windows) falsche NAT und Firewall Settings hatte. Vielleicht hilft dir die Info weiter..

**Comment by motom001** [comment]
@Schnillo: 
Welches Sipphone nutzt Du?
Welche DoorPi-Version nutzt Du?

**Comment by Schnillo** [comment]
Hi Thomas, sorry habe gerade erst gesehen das du mir geschrieben hast.

Siphone = linphone

Doorpi = aktuell

 

Es scheint aber ein allgemeines Problem zu sein, das Internet ist voll solcher Probleme.

 

Von: Thomas [mailto:notifications@github.com] 
Gesendet: Donnerstag, 10. September 2015 10:37
An: motom001/DoorPi <DoorPi@noreply.github.com>
Cc: Schnillo <andreas@schwarz-ketsch.de>
Betreff: Re: [DoorPi] Mikro an der Aussenstation (#104)

 

@Schnillo <https://github.com/Schnillo> : 
Welches Sipphone nutzt Du?
Welche DoorPi-Version nutzt Du?

**Comment by motom001** [comment]
Es gibt auf jeden Fall einen Fehler im Quellcode:
https://github.com/motom001/DoorPi/blob/master/doorpi/sipphone/linphone_lib/CallBacks.py#L156
An der Stelle durchläuft der ankommende Anruf, sofern bereits einer bestanden hat, das zweite mal die Verbindung (erste Mal auf Zeile 142). Entweder in 156 ein elif oder ob bei 142 nur beenden ohne neu zu verbinden.

Ob der diese Auswirkung hat, müsste jemand anderes bitte testen (meine Umgebung ist laut Erfahrungen nicht repräsentativ).

**Comment by pistreamer** [comment]
Hallo Thomas, ich habe gerade Linphone Tests durchgeführt und die Tests gingen ohne Änderungen ohne Probleme. Ich habe bemerkt, dass ich nicht in die Abfrage von 156 Springe, ich denke das ist ein Teil für Verbindungsprobleme oder nicht? Wenn ja ist das nicht gerade einfach zu testen. 

Jedenfalls habe ich folgendes gerade nochmal getestet:

SIP Server (sip.linphone.org Accounts) und extra dann noch Asterisk Server (lokal):
- Anruf an DoorPi mit 2 Clients einmal mit Admin und einmal ohne (ohne Admin kein Durchkommen)
- Anruf an DoorPi mit 2 Admins (der als letzter Anruft wird automatisch verbunden, der alte getrennt)

Zusätzlich habe ich noch alles ohne Accounts getestet, dh. ohne Server und nur mit lokalen Client, konnte keine Fehler im Trace entdecken.

Client 1: Zoiper am Android Smartphone (Qualität einwandfrei)
Client 2: Linphone Windows 8.1 (Obwohl schlechte Sprachqualität!)

**Comment by motom001** [comment]
Lasse ich den Issue noch offen, wenn der Initial-User gelöscht ist?
Wen frage ich dann, wann das Thema erledigt ist?

**Comment by maxkr2** [comment]
Mach ihn zu. pistreamer hat ja div. Szenarien getestet und es nicht nachstellen können. Wenn es noch mal Thema ist wird derjenige schon ein Issue erstellen...?
