### ISSUE TITLE
Installation klappt nicht

### ISSUE THREAD

**Issue by redfox1977** [motom001/DoorPi#109]
Hallo,
Ich habe gestern versucht DoorPi auf einem neuen rasbian zu installieren, und habe mich nach der Installationsanleitung gehalten. DoorPi startet auch, aber wenn ich mich versuche über den Browser doorpi aufzurifen, kommt immer ein Loginrequest.
Im debugmonitor steht dann immer "section AREA_public not found in configfile" und das er die login.html nicht findet!

**Comment by motom001** [comment]
Benutzername "door"
Passwort "pi"

**Comment by redfox1977** [comment]
Guten Abend,
Ja genau das ist das 2. Problem. Ich hatte gestern das 1. Mal mit der neuen Installation zu tun.
Das erste was ich sagen muss ihr alle macht einen Tollen Job! das Projekt hat sich in letzter Zeit extrem nach vorne entwickelt. 
Aber das mit der Installation verstehe ich nicht! 
Früher hat man das Setup-Script aufgerufen und dann war alles in /hone/DoorPi installiert und man konnte die Config nach belieben anpassen.
Nun nach der Installation finde ich dort nichts mehr, alles liegt in tmp ?!?!? das Verzeichnis wird bekanntlich von Linux automatisch aufgeräumt.
Die Konfigdatei wird in /tmp/doorpi/config/ gespeichert und wenn man diese ändert wird sie beim nächsten Neustart überschrieben!?!?!?!
Wenn ich versuche den demon zu installieren und ihm die Konfigdatei in /etc/DoorPi/doorpi/config mitgebe wird das Konsequent ignoriert! Was mache ich falsch?! Warum wird das Programm nicht in /opt installiert und die Konfig kommt dann in /etc oder auch in opt?
Und wo landet das Programm jetzt? konnte ich aus den Scripts nicht herrauslesen!?!

MFG redFOX

**Comment by redfox1977** [comment]
Hallo...
Ich geb ja nicht so leicht auf, ich habe mir jetzt eine neue SD-Karte geschnappt, raspian drauf geschmissen, alles auf den neusten Stand gebracht und dann versucht doorpi noch mal zu installieren! nach Anleitung über GIT:
Raus kam:
root@doorpi:/home/pi# doorpi_cli --trace
Traceback (most recent call last):
  File "/usr/local/bin/doorpi_cli", line 9, in <module>
    load_entry_point('DoorPi==2.4.0.8', 'console_scripts', 'doorpi_cli')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named doorpi.main

Was mach ich falsch???

**Comment by Nea74** [comment]
Bitte installiere dir noch den Python-Daemon
"sudo pip install daemon"
Das sollte dein Problem lösen.

**Comment by motom001** [comment]
in der aktuellen requirements.txt ist es auch enthalten, somit würde es bei neuen Installationen automatisch mit installiert werden.

**Comment by Nea74** [comment]
Müsste sich ebenfalls erledigt haben:
