### ISSUE TITLE
Umsetzung BASE_PATH im Zusammenhang mit daemon

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#113]
An dem Thema Autostart arbeite ich gerade mit aller Macht.
Das Problem mit der neuen Installation (über setup.py) ist, dass es anders installiert wird.
Es liegt also bei den meisten unter:
/usr/local/lib/python2.7/dist-packages/doorpi
/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.0.dist-info
/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.0-py2.7.egg

In der letzten Version (2.4.1.0) hab ich versucht, den home-Path des User zu bekommen, der mit dem System arbeitet:
https://github.com/motom001/DoorPi/blob/9f55bf79d76fbb39b5eb04e66b61ed05c8326a1a/doorpi/doorpi.py#L95

Also wird doorpi_cli als pi gestartet und Base_Path ordentlich aufgelöst zu /home/pi
Dort wird noch dar Name des Package dran gehangen und ergibt somit
/home/pi/DoorPi
Dort werden alle Ordner sauber angelegt (conf, media, records, ...) und ergeben folgende Struktur:
/home/pi/DoorPi/conf/doorpi.ini
/home/pi/DoorPi/conf/eventlog.db
/home/pi/DoorPi/media/ShortDialTone.wav
/home/pi/DoorPi/records/*.wav

Nun kommt das Problem - als daemon läuft es als root - das home-Verzeichnis von root kann nicht abgefragt werden und springt zurück auf /tmp/DoorPi
Dort kann aber keine Config etc liegen, da es nach dem nächsten Neustart weg ist.
Ich will aber die Pfade auch nicht hart in den Qullcode eintragen - sonst gibt es Probleme bei unterschiedlichen Distributionen und erst wenn Windows dazu kommt.
In der Config können die Pfade nicht stehen, da schon die Config in dem Pfad gesucht werden müsste.
Also müsste es theoretisch als Parameter mitgegeben werden.
Ich wollte aber keine Zwang-Parameter mehr, da mich das in Probleme bringt beim Software-Test (z.B. travis-ci)

Also drehe ich mich gerade im Kreis - wie man es macht, wird es verkehrt...

Vorschläge?

**Comment by Nea74** [comment]
Guten Morgen, auch hier kann geschlossen werden.
