### ISSUE TITLE
Noch immer Probleme mit dem E-Mail Versand aus DoorPi heraus.

### ISSUE THREAD

**Issue by Nea74** [motom001/DoorPi#129]
Vieleicht liegt es einfach an meinem Provider 1und1 das hier keine Mails versendet werden. So wie es aussieht kann DoorPi sich nicht auf den smtp Server von 1und1 anmelden. Ich habe mir sendEmail installiert und eingerichtet hier geht es nun mit folgender Befehlskette und Parametern: 
Dies gilt nur exemplarisch da hier erst ein Backup ausgelöst wird und der Status dann per sendEmail verschickt wird.
```sudo /usr/local/bin/raspiBackup.sh -p /backup/Backup-DoorPi -t tar -k 3 -s sendEmail -e empfaenger@mailadresse.de -E '-f Versender@mailadresse.de -s smtp.1und1.de:587 -xu Benutzername -xp Passwort -o tls=yes' ```
Hat noch jemand so Probleme wie ich?
Was versendet DoorPi hier alles?
Besteht die Möglichkeit hier auch sendEmail zu DoorPi hinzuzufügen?

**Comment by Tobi-BPi** [comment]
Hi, 
direkt helfen kann ich dir bestimmt nicht aber ich hatte auch schon Probleme mit meinen web.de
account. 
Dann testete ich meinen Gmail account und auch der funktionierte anfänglich nicht. 

Mein Problem war, auf das mich Gmail aufmerksam machte, da der Server erkannte das es sich um einen "maschinellen Eingriff" handelte, also die Mail wohl nicht von mir selber/persönlich versendet wurde.
Somit hatte Gmail einen unberechtigten Zugriff erkannt und sperrte meinen Mailversand.

Jetzt geht es komischerweise... habe mir ein neues Konto bei Gmail angelegt und zwar direkt über den Browser im Raspbian.

Funktioniert nun ohne Probleme.
Web.de geht immer noch nicht, dass kommt mir vor als wenn die das Abblocken.

mfg
Tobi

**Comment by Nea74** [comment]
Guten Morgen Tobi, danke für Deine Antwort. Seltsamerweise funktioniert es ja wenn ich über sendemail eine mail verschicke. Nur mit dem Mail Prog. das in DoorPi integriert ist will es nicht gehen.
Ich werde mir das nochmal genau anschauen, vieleicht fehlt bei mir noch ein Parameter.

**Comment by max337** [comment]
Hi Nea74, hatte ein ähnliches problem mit Strato. Hatte sich dadurch lösen lassen, dass ich den alternativen Port 587 an stelle von 465 verwendet habe.

Vllt. geht das ja auch bei 1&1?

Gruß,
max

**Comment by Nea74** [comment]
Hallo max337,
diesen Port habe ich auch schon probiert leider keinen Erfolg gehabt. Aber Danke für Deine Antwort.

Gruß Nea

**Comment by Nea74** [comment]
Da keiner ein Problem hatte , außer ich, schliese ich diesen issue.
