### ISSUE TITLE
DoorPiWeb zeigt die Installierten Module und die Konfig nicht mehr

### ISSUE THREAD

**Issue by cemerich** [motom001/DoorPi#135]
Hallo,
nach der Installation von 2.4.1.6 sehe ich ii DoorPiWeb die installierten Module im Dashboard nicht mehr, und bei der Konfig sagt er nur loading und zeigt keinen einzigen Eintrag.

Habe nach der Anleitung (inklusive Deinstallation) die development Version probiert, habe aber das gleiche Verhalten. Habe auch die neueste Version von DoorPiWeb ausprobiert, jedoch mit dem gleichen Ergebnis. Meine config Datei hat die Endung cfg, kann das eine Auswirkung haben oder habe ich eine Environment Variable nicht gesetzt wekche von DoorPiWeb benötigt wird.

Danke Christian

**Comment by motom001** [comment]
Ich teste das heute Abend

**Comment by cemerich** [comment]
Danke!!

 

Von: Thomas [mailto:notifications@github.com] 
Gesendet: Mittwoch, 07. Oktober 2015 10:03
An: motom001/DoorPi
Cc: cemerich
Betreff: Re: [DoorPi] DoorPiWeb zeigt die Installierten Module und die Konfig nicht mehr (#135)

 

Ich teste das heute Abend

—
Reply to this email directly or view it on GitHub <https://github.com/motom001/DoorPi/issues/135#issuecomment-146106924> .  <https://github.com/notifications/beacon/AGczhJi3WeEMN1MWIl805-AhHJH4QXNZks5o5MkegaJpZM4GKU9l.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by cemerich** [comment]
Hallo Thomas,
ich habe den Grund gefunden!!
Ich hatte in einer Email Ausgabe im Text ein Ä.
"20 = mailto:christian.emerich@aon.at,DoorPi,Taster 1 betätigt --> Nummer 9000 wird gewählt!"

Daraufhin wurde beim einlesen der Konfig ein Json Fehler generiert und sowohl die Konfig als auch die Module nicht geladen. Die Email wurde jedoch korrekt ausgegeben.

**Comment by Nea74** [comment]
closed.
