### ISSUE TITLE
Basepath und default ini datei unklar

### ISSUE THREAD

**Issue by cspann** [motom001/DoorPi#138]
Hallo,

Ich wollte gerade Doorpi nach der Installationsanleitung installieren und bin beim ersten starten schon hängen geblieben. Zwei Punkte sind mir aus der Installationsanleitung nicht klar:
1. Wie und wo soll der BASE_PATH gesetzt werden.  Standardmäßig zeigt der auf /usr/local/etc/DoorPi. Dort kann aber doorpi nicht schreiben als user.
2. Gibt es eine default config Datei mit Kommentaren? Falls ja wo?

Wenn diese Punkte in der Installationsanleitung erklärt würden, würde das sicher vielen weiterhelfen.

Gruß

**Comment by motom001** [comment]
Die Anpassung von BASE_PATH sollte nicht mehr nötig sein, da das tpl-File nur noch Platzhalter enthält, die nach der Installation im daemon-File korrekt gefüllt sein sollten.
Ich prüfe das noch einmal und würde entsprechend die README anpassen (oder hast Du noch einen Ort gesehen, wo es steht?)

**Comment by cspann** [comment]
Hallo,
Ich konnte den Sinn bzw. die Aufgabe des .tpl files auf die schnelle jetzt nicht ergründen. Folgendes habe ich bis jetzt herausgefunden:

1. Ich starte doorpi als user, das klappt auch problemlos, der webserver läuft dann unter 8080 was kein problem darstellen sollte. Abgesehen von der Sicherheitsdebatte steht das so in der Readme, dass man door_pi als user starten soll. Das solltest Du dann ändern, wenn gewünscht, ist aber nicht notwendig.

2. Der BASE_PATH den ich meine wird aus dem Feld doorpi_path in metadata.py gelesen und in das Feld BASE_PATH von doorPi geladen und stellt den Pfad dar, wo DoorPi seine configdatei ablegt. Da ich door_pi als user startete und standardmäßig in metadata.py /user/local/etc/ ablegen möchte, schlägt das fehl. Ich habe nun den Wert in metadata.py wie folgt abgeändert:  

   ```doorpi_path = os.path.join(os.path.expanduser("~"), package)```  
  
  Nun erzeugt DoorPi seine config datei in ~/DoorPi und funktioniert erstmal normal. Ich bin aber von meinem setup noch etwas entfernt.

3. Der Standard User und das Standard Passwort für den Webserver stehen nirgends in der Readme. Ich musste sie mühsam im source code greppen.

**Comment by motom001** [comment]
bitte neu eröffnen, wenn noch aktuell - Danke!
