### ISSUE TITLE
Check for pip Problemlösung in Readme aufnehmen

### ISSUE THREAD

**Issue by cspann** [motom001/DoorPi#139]
Die initiale Installation von Doorpi lief bei mir seltsamerweise durch, als ich aber in metadata.py den door_pi path auf einen schreibbaren Ort setzte und DoorPi nochmal installieren wollte, brach die Installation aufgrund der fehlerhaften Abhängigkeitsgeschichte im vorinstallierten PIP in Raspbian ab. 

Erst der manuelle Aufruf von 
```
      sudo python get_pip.py
```
und die resultierende Neuinstallation einer aktuellen pip Version haben das Problem gelöst. 

Kann das Verhalten jemand verifizieren oder erklären, dann würde ich einen entsprechenden Hinweis in die Readme aufnehmen und einen Pullrequest erstellen

**Comment by motom001** [comment]
Warum wolltest Du den Pfad in der metadata.py anpassen?

**Comment by motom001** [comment]
Hängt sicherlich mit #138 zusammen - oder?

**Comment by motom001** [comment]
Du arbeitest einmal mit sudo und einmal ohne - kann das sein?

DoorPi sollte, wenn möglich, immer unter sudo Rechte laufen, sonst wird es schwer z.B. den Webserver an den Port zu binden.

**Comment by cspann** [comment]
Hi, ich denke nicht, da ich die Installation jeweils natürlich als sudo aufgerufen habe. Ich habe ledier gerade nicht die Zeit um den Pi nochmal jungfräulich aufzusetzen und zu versuchen den Fehler reproduzieren. pip wurde auf jeden Fall in einer neuen Version installiert.

**Comment by motom001** [comment]
Fehler kann ich unter jessie reproduzieren, unter wheezy nicht. 
Eine Deinstallation des apt Paketes python-pip habe ich in der installationsdoku aufgenommen... 
http://board.doorpi.org/showthread.php?tid=8
