### ISSUE TITLE
es fehlt ein call timeout (wenn keiner das Telefongespräch annimmt)

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#14]
In der Config sollte einstellbar sein, wie lange DoorPi versucht die Telefone anzurufen bevor es aufgibt.
Im Standard sind es 120 Sekunden, das ist viel zu lange.

**Comment by motom001** [comment]
Zwischenstand: Event-Handler steht, jetzt überarbeite ich aber gerade das pjsua Modul. Dabei wird diese Anforderung dann mit umgesetzt.

**Comment by motom001** [comment]
calltimeout ist in pjsua-call implementiert und wird mit jedem timetick aufgerufen. Passende config-Einträge sind:
[SIP-Phone]
call_timeout = 30
max_call_time = 120

Beide Angaben sind in Sekunden und stellen hier auch gleich die default-Werte dar.
call_timeout definiert die max. Zeit bis der Anruf entgegengenommen wird. Klingel wird gedrückt aber keiner geht ran -> nach 30 Sekunden wird das Gespräch beendet.
max_call_time ist die max. Gesprächszeit. Also Zeit ab dem Punkt "Gespräch wurde entgegengenommen".

**Comment by motom001** [comment]
@pmunz - Kannst Du das bitte in Verbindung mit Asterisk testen?
Danke...

**Comment by pmunz** [comment]
Hallo , natürlich teste ich heute .


Philipp Munz. web/soft & Hardware Development. - Mac - Mobile - iPhone - Windows - 
Perfect Websolutions | Sinnhubstrasse 14 | 5020 Salzburg Austria 
Mobile: +43 (0) 676 9219693
For advertising - info, contact: our office | Twitter: click... | Download Mail Public Keys
