### ISSUE TITLE
Einstellungen piface , Please Help !

### ISSUE THREAD

**Issue by MichelSBG** [motom001/DoorPi#141]
Hallo ,
erstmal super geniales Projekt, ich freu mich das ich es gefunden habe . Danke dem Programmierer und dem TEAM !

Mein Problem:

ich hab soweit alles geschafft, nur ich hab bezüglich piface einige unklarheiten

alles installiert und mit 
python3 /usr/share/doc/python3-pifacedigitalio/examples/blink.py
und auch python 2 getestet , das piface board sollte passen.!

nur was und wie muss ich die doorpi.ini einstellen ?

bin mit nana /usr/local/etc/Doorpi im ini file aber mir fehlt der Paln mit den Pins usw.

kann mir wer einen tipp oder einen auszug seiner ini datei schicken ?

ich bekomm es nicht zum laufen. danke

meine ini datei 

....
[keyboards]
pifaceboard = piface

[pifaceboard_keyboard]

[pifaceboard_OutputPins]

[pifaceboard_InputPins]

[DTMF]

[Group]
administrator = door

[User]
door = pi

[WritePermission]
administrator = installer

[ReadPermission]

**Comment by MichelSBG** [comment]
ich hab auch noch das thema das ich nicht weis wie ich mit DTMF und eintrag in das ReadPermission umgehen soll.
angemerkt ich benutze einen Asterisk Server @ home

**Comment by MichelSBG** [comment]
Hallo, Danke ich hab das soweit verstanden und Funktioniert bestens .-) 
Für mich ist im moment nur die Frage wie ich [ReadPermission] Richtig setzen kann ?
Danke

**Comment by MichelSBG** [comment]
Hab alles hin bekommen, DTMF und die Pin geschichte . :-)

**Comment by motom001** [comment]
Nett wäre noch zu schreiben wie du es geschafft hast, dann findet der nächste schneller die Lösung?

**Comment by motom001** [comment]
Nett wäre noch zu schreiben wie du es geschafft hast, dann findet der nächste schneller die Lösung?
