### ISSUE TITLE
IP-Adresse Ausgeben

### ISSUE THREAD

**Issue by MichelSBG** [motom001/DoorPi#143]
Hallo, 
Ist es Vielleicht auch möglich die vom Raspberry pi bezogene IP Adresse per mail zu versenden ?
wenn das gerät startet wäre super diese per e-mail mit zu bekommen.
Statische Adressen sowie auch DHCP Adressen ?
Danke

**Comment by motom001** [comment]
Bisher nicht - aber nette Idee...

**Comment by motom001** [comment]
Rückfrage :
Welche IP erwartest du? Die im lokalen Netzwerk oder die öffentliche deines Internetanschlusses?

**Comment by motom001** [comment]
eventuell ein Teil für "system" -> #170
