### ISSUE TITLE
Frage zu den Events

### ISSUE THREAD

**Issue by Steee27** [motom001/DoorPi#145]
Ich habe mich schon dumm und dämlich gesucht, die verfügbaren Events mit Beschreibung zu finden,  wo kann ich diese finden? Bitte um Hilfe

**Comment by ikarusatgithub** [comment]
Habe auch ein Dokumentationsproblem (bin aber auch erst seit 2 Abenden mit DoorPi dran; super Projekt) für das es hoffentlich eine Lösung gibt:

Ich habe versucht einen eigenen Event zu erstellen, 

EVENT_OpenDoorEV
10	hangup:1
20	out:OpenDoor,1,0,3

der aufgerufen werden soll, wenn per SiP Phone ein Befehl gegeben wird.

DTMF
*	EVENT_OpenDoorEV

Der out:OpenDoor,1,0,3 Befehl alleine nach dem * Komando  funktioniert.

Der Event ist auch unter Status: aktive Events eingetragen:
OpenDoorEV	1	HangupAction with args ('1',) and kwargs {}
OpenDoorEV	2	OutTriggeredAction with args () and kwargs {'stop_pin': 'NoStopPinSet', 'end_value': '0', 'timeout': 3.0, 'pin': 'OpenDoor', 'start_value': '1'}

Danke für Lösungsvorschläge.

**Comment by majorkalina** [comment]
@Steee27 DoorPi web ist sehr guenstige Quelle fuer das.

**Comment by motom001** [comment]
bitte neu eröffnen, wenn noch aktuell - Danke!
