### ISSUE TITLE
 SIP-Problem - Exception NameError: 'linphone.ProxyConfig'

### ISSUE THREAD

**Issue by thgorjup** [motom001/DoorPi#146]
Hallo, ich habe es bereits im Forum gepostet, aber hier ist es besser aufgeboben.
Ich habe DoorPi und linphone4raspberry-3.8.0 installiert. Der Aufruf mittels --trace funktioniert auch, aber sobald ich meine eigene Config verwende, erhalt ich folgende Fehlerausgabe, sobald ich in der doorpi.ini im Abschnitt [SIP-Phone] einen username und ein passwor verwende.

Hier erstmal die doorpi.ini

[SIP-Phone]
firewallpolicy = PolicyNoFirewall
sipphonetyp = linphone
sipserver_server = 192.168.179.1
sipserver_username = 621
sipserver_password = raspberry
identity = DoorPi
realm = server
#log.level = 5
#log.console_level = 5
local_port = 5060
ua.max_calls = 2
call_timeout = 20
max_call_time = 120
dialtone = /usr/local/etc/DoorPi/media/ShortDialTone.wav
dialtone_renew_every_start = False
echo_cancellation_enabled = False
playback_device = ALSA: bcm2835 ALSA
capture_device = ALSA: USB PnP Sound Device
audio_codecs = PCMA,PCMU
video_codecs = VP8
video_device =
video_display_enabled = False
video_size =
records = /usr/local/etc/DoorPi/records/!LastKey!/%Y-%m-%d_%H-%M-%S.wav
record_while_dialing = false

.. und hier die Fehlermeldung nach dem Aufruf:
doorpi_cli --trace --configfile /home/pi/DoorPi/conf/doorpi.ini

-------------------------------------------------------------------
2016-01-23 11:01:28,714 [ERROR]         [doorpi.main] Exception NameError: 'linphone.ProxyConfig' object has no attribute 'identity_address'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.6-py2.7.egg/doorpi/main.py", line 153, in main_as_application
    try:                        doorpi.DoorPi(parsed_arguments).run()
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.6-py2.7.egg/doorpi/doorpi.py", line 234, in run
    if not self.__prepared: self.prepare(self.__parsed_arguments)
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.6-py2.7.egg/doorpi/doorpi.py", line 151, in prepare
    self.sipphone.start()
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.6-py2.7.egg/doorpi/sipphone/from_linphone.py", line 270, in start
    conf.get(SIPPHONE_SECTION, "identity", 'DoorPi'), username, server)
AttributeError: 'linphone.ProxyConfig' object has no attribute 'identity_address'
2016-01-23 11:01:28,725 [DEBUG]         [doorpi.doorpi] destroy doorpi

-------------------------------------------------------------------

Kann mir bitte jemand bitte helfen und mit mitteilen, was hier flasch ist?
Ich habe bereits im Forum und im Web gesucht, aber keine Lösung gefunden.
Ich habe nur die Fritzbox und keinen Asterisk Server. Mit iSip auf meinem iPhone konnte ich mit erfolgreich mit den o.g. Zugangsdaten eintragen. Und JA, die IP 192.168.179.1 ist richtig.
Ich habe ein anderes Subnet als das default gewählt.

Danke und Gruß
Thomas

**Comment by chklein** [comment]
Hallo, ich habe exakt das selbe Problem.
Hat mittlerweile jemand eine Lösung oder einen Hinweis wonach ich noch suchen kann?
Ich habe den Eindruck, dass linphone nicht gefunden wird, bzw. eine falsche Version davon verwendet wird. Grundsystem ist minibian jessie.

Danke und Gruß
Christoph

**Comment by motom001** [comment]
Linphone in Version min. 3.8.5 installieren und alles ist gut :)
Ist beim Wechsel von 3.8.0 auf 3.8.5 durch Linphone geändert wurden...

Siehe auch: http://www.forum-raspberrypi.de/Thread-haussteuerung-doorpi-voip-wechselsprechanlage-tuersprechanlage-mit-video-support?pid=173487#pid173487

**Comment by chklein** [comment]
Vielen Dank. Ich habe inzwischen den Quellcode auf 3.8.0 angepasst, das läuft. Wie kann ich nun nachträglich linphone upgraden? Vielen Dank für die Hilfe
Gruß Christoph

**Comment by motom001** [comment]
Dann hast du das Problem wieder - besser wäre das Update von linphone und die Änderungen am Quellcode wieder rückgängig machen
