### ISSUE TITLE
Update von Wheezy geht nicht mehr. Was muss für Jessie angepasst werden?

### ISSUE THREAD

**Issue by aule01** [motom001/DoorPi#147]
Hi,
ich habe heute eine neue SD-Karte mit Wheezy bestückt (2015-05-05-raspbian-wheezy.img). Das Update auf den letzten Stand schlägt nun fehl:
W: Failed to fetch http://raspberrypi.collabora.com/dists/wheezy/rpi/binary-armhf/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.

Sieht danach aus, als müsste man nun  Jessie verwenden. Die Readme-Datei meint aber:
"Es wird aktuell empfohlen DoorPi nur auf Raspbian Wheezy zu installieren da das Installationskrip für Raspbian Jessie angepasst werden muss."
Was ist hierzu nötig?

Vielen Dank im Voraus für eure Hilfe

Uwe

**Comment by msmolny** [comment]
Probier mal, ob Dir das hilft: http://www.forum-raspberrypi.de/Thread-raspbian-error-403

**Comment by aule01** [comment]
Danke, werde ich probieren. Das ändert aber nichts daran, dass diese Updates vor ca. 6 Wochen noch problemlos verfügbar waren. Damit rückt ein Wechsel auf Jessie immer näher, weil Wheezy nicht mehr problemlos aktualisiert werden kann.
Das war der Grund für meine Frage, was dem Script für Jessie eigentlich fehlt...

**Comment by motom001** [comment]
> Das war der Grund für meine Frage, was dem Script für Jessie eigentlich fehlt...

Das würde mich auch interessieren...

**Comment by drtp** [comment]
ich fand [diese](http://www.forum-raspberrypi.de/Thread-haussteuerung-doorpi-voip-wechselsprechanlage-tuersprechanlage-mit-video-support?pid=192761#pid192761) Anleitung sehr hilfreich. Damit hat die Installation von DoorPi unter Jessie einwandfrei bei mir geklappt.

**Comment by motom001** [comment]
Hab es probiert, dokumentiert und hier veröffentlicht :
http://board.doorpi.org/forumdisplay.php?fid=4

Rückmeldung erwünscht ob ich den Issue schließen kann...

**Comment by aule01** [comment]
Hat geklappt, vielen Dank.
