### ISSUE TITLE
doorpi.ini vs. doorpi.cfg

### ISSUE THREAD

**Issue by drtp** [motom001/DoorPi#148]
Hallo,

mir ist aktuell nicht klar, worin die Unterschiede beider Konfigurationsdateien liegen? Habe mir die aktuelle Version 2.4.1.6 von DoorPi installiert und mir wurde automatisch die Datei doorpi.ini angelegt. Brauche ich für events oder dergleichen noch die doorpi.cfg oder wird das mittlerweile alles über die doorpi.ini konfiguriert?

Gruß,

Thorsten

**Comment by motom001** [comment]
Ist nur ein Unterschied im Namen, inhaltlich ist alles gleich... 
Wie heißt es so schön? Historisch gewachsen... 

Aktuell nutze ich immer doorpi.ini
