### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Das-Flippi** [motom001/DoorPi#149]
Hallo zusammen,

Ich bin erst neu in die ganze Materie eingestiegen und habe wirklich so gut wie keine erfahrung.
Ich habe doorpi schritt für schritt nach Anleitung installiert. Jetzt hänge ich nur an dieser Stelle:
Doorpi als systemdienst installieren. Da bekomme ich diese meldung

`sudo cp /home/DoorPI/docs/service/doorpi /etc/init.d/`
`cp: Aufruf von stat für „/home/DoorPI/docs/service/doorpi“ nicht möglich: Datei oder Verzeichnis nicht gefunden`

Wie gesagt sorry falls es ein dummer fehler oder ähnliches ist aber ich bin total der anfänger.

**Comment by motom001** [comment]
Verweis auf :
http://board.doorpi.org/showthread.php?tid=12&pid=33#pid33

**Comment by bgewehr** [comment]
Die Datei doorpi im Verzeichnis service heißt dort doorpi.tpl. Somit müsste diese Zeile der Anleitung lauten:
    
    sudo cp /home/DoorPI/docs/service/doorpi.tpl /etc/init.d/doorpi

**Comment by motom001** [comment]
https://www.doorpi.org/forum/thread/1478-installation-mit-aktuellem-raspberryos/
