### ISSUE TITLE
Camera mounting in Gira TX44

### ISSUE THREAD

**Issue by bgewehr** [motom001/DoorPi#160]
Hi!

Great Project!

I just finished a camera mount for the Gira TX44 camera dome

Gira 141565 Abdeckung Farbkamera Gira TX_44, alu https://www.amazon.de/dp/B0020EJQNQ/ref=cm_sw_r_cp_awd_xqHexbKHPCKX8

That is a clear glass dome without the silver camera inside, picture is misleading.

So we need a custom camera mount, right?

Here it is:

![](http://i.imgur.com/i8QMyEV.jpg)

![](http://i.imgur.com/yd8dHom.jpg)

Printed on 3dhubs.com for 15€.

**Comment by motom001** [comment]
Backlink:
http://www.doorpi.org/forum/thread/112-kameradom/?postID=1642#post1642
