### ISSUE TITLE
Anleitung ist an einer Stelle irreführend

### ISSUE THREAD

**Issue by incredibleXE** [motom001/DoorPi#169]
unter https://github.com/motom001/DoorPi/wiki/Configfile#keyboards führte der Wert `piface` in die Irre.
Ich dachte in der Konfiguration muss `piface = piface` stehen. Tatsächlich funktioniert es nun mit `prodsystem = piface`

Ich bin mir nicht sicher, wie man es besser ausdrücken kann. Dir fällt bestimmt etwas ein.
Vielleicht mit ein zwei Beispielen?

Vielen Dank,
Gruß,
Fabian

**Comment by motom001** [comment]
Auch die Definition von `piface = piface` funktioniert, wenn die restliche Konfiguration dem angepasst wird. Es muss nicht prodsystem genannt werden.
