### ISSUE TITLE
FriendlyElec NanoPi Neo Kompatibilität

### ISSUE THREAD

**Issue by aAdrianCc** [motom001/DoorPi#174]
FriendlyElec hat das RPi.GPIO Modul auf den AllWinner H3 SoC portiert. Das offizielle Ubuntu Core Image beinhaltet das angepasste Python Modul, aber dieses wird bei der Installation vom offiziellen Raspberry Pi RPi.GPIO Modul überschriben.

**Comment by motom001** [comment]
Vor der Installation die entsprechende Zeile in der requirements.txt entfernen und gut ist :)
https://github.com/motom001/DoorPi/blob/master/requirements.txt#L2
