### ISSUE TITLE
sipphone liblinphone einbinden

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#18]
Anfrage per Mail:
Bitte auch anderes sipphone anbieten (z.B. liblinphone)

**Comment by motom001** [comment]
Ich habe Probleme mit liblinphone. Die 32-Bit Snapshots sind 64-Bit Snapshots und lassen sich auf dem Pi nicht starten. Das kompilieren vom liblinphone habe ich bisher nicht hinbekommen.
Eventuell kann noch jemand unterstützen?
Installationsanleitung für den Python Wrapper von liblinphone unter Linux:
https://www.linphone.org/snapshots/linphone-python/
Ich kann auch jemanden vermitteln, der sich damit schon beschäftigt, aber 4 Augen sehen immer mehr als zwei...

**Comment by hermanthegerman2** [comment]
Können wir folgende Quelle auch nehmen?
git clone git://git.linphone.org/linphone.git --recursive

**Comment by motom001** [comment]
Leider nein, da dort der Python Wrapper fehlt. Der hier geht:
git clone git://git.linphone.org/linphone-cmake-builder.git

**Comment by hermanthegerman2** [comment]
nach einem:
make build-python -- -DCMAKE_BUILD_TYPE=Release
bekomme ich folgenden Fehler:
make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/linphone-cmake-builder/WORK/cmake-python/Autotools
-- Using configuration file '/home/pi/linphone-cmake-builder/configs/config-python.cmake'
-- Including builder antlr3c
-- Including builder polarssl
-- Including builder bellesip
-- Including builder ortp
-- Including builder gsm
-- Including builder opus
-- Including builder speex
-- Including builder ffmpeg
-- Including builder vpx
-- Including builder v4l
-- Including builder srtp
-- Including builder xml2
-- Including builder bzrtp
-- Including builder ms2
-- Including builder sqlite3
-- Including builder linphone
CMake Error at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:644 (message):
  External project "TARGET_linphone_builder" has no stamp_dir
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:856 (ExternalProject_Get_Property)
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1331 (_ep_get_step_stampfile)
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1545 (_ep_add_configure_command)
  configs/config-python.cmake:159 (ExternalProject_Add)
  CMakeLists.txt:58 (include)


-- Configuring incomplete, errors occurred!
Makefile:80: recipe for target 'build-python' failed
make: *** [build-python] Error 1

warum ?

**Comment by pmunz** [comment]
linphone_builder" has no stamp_dir
Das der Grund ?

**Comment by pmunz** [comment]
Vor dem make Befehl ins config oder make file sehen und dir die Variable stamp_dir suchen , gegebenfalls abändern / Rechte vergeben 
>

**Comment by hermanthegerman2** [comment]
was heisst das konkret bzw. was muss ich beim make zusätzlich angeben?

**Comment by motom001** [comment]
Ich glaube pmunz ist auch noch nicht weiter.
Ich habe aufgegeben und bin froh, dass sich jetzt Profis damit beschäftigen...

**Comment by hermanthegerman2** [comment]
komisch mit einem banalen make entgegen der Empfehlung aus der README.python.md läufts bis jetzt noch ganz gut ..... bis dann ......

**Comment by hermanthegerman2** [comment]
abgebrochen! ich komme da auch nicht weiter !

**Comment by pmunz** [comment]
gut ding braucht weile ;) wenn es so einfach wäre dann könnte man eh alles an einem tag entwikeln *grins* was hast du für paket downgeloadet und welche dependencies hat du installiert ?
*** libtool libglib2.0-dev libgtk2.0-dev libspeex-dev libantlr3c-dev antlr3 libspeexdsp-dev libswscale-dev libXv-dev mesa-common-dev libglew-dev libortp-dev ***

**Comment by hermanthegerman2** [comment]
dieses Repository / git clone git://git.linphone.org/linphone-cmake-builder.git
sudo apt-get install build-essential

wie weit bist Du gekommen?

**Comment by pmunz** [comment]
ich hab es aus einer anderen quelle, ich werd deine gleich mal testen....

**Comment by hermanthegerman2** [comment]
Viel Erfolg!

**Comment by pmunz** [comment]
linphone zu kompilieren brachte leider noch keinen erfolg :-(
es wäre im moment nur die installation durch
terminal-based version of the software linphone
sudo apt-get install linphone-nogtk
möglich aber eben nur über das os system
nach der installation mit : linphonecsh -h

ich werde es jetzt mal mit anderen version versuchen um es zu kompilieren, vielleicht versionsbedingt....

**Comment by motom001** [comment]
Ich wollte mal nach dem Stand fragen - hat es schon jemand hinbekommen?

**Comment by hermanthegerman2** [comment]
Hier die Antwort von Simon MORLAT <simon.morlat@belledonne-communications.com> 
Hi Hermann,

The current python wrapper isn't supported for ARM devices, only x86.
The build procedure we've developed for the python module doesn't support cross-compilation.

This is something we are able to do, though.

Let me know if you need us to establish a quotation to add cross-compilation and ARM support to the python wrapper.

Best regards,

Simon

Ich denke wir stellen die Anforderung noch zurück oder konzentrieren uns auf andere Alternativen als pjsua und linphone.

Vorschläge? Ideen?

**Comment by pmunz** [comment]
Ich habe bereits eine ARM Version gebaut , habe die von IOS iphone 
Abgewandelt 
Vielleicht kann ich sie heute noch freigeben 

Lg

**Comment by hermanthegerman2** [comment]
Coole Sache! ... es geht voran ...

**Comment by pmunz** [comment]
hallo,
nach einer woche harter arbeit und vielen versuchen ist es jetzt so das wir das kompilieren geschafft haben. Sich linphone importieren lässt , aber leider wieder ein fehler aufgetreten ist , ich glaube selbst wenn wir das hin bringen haben wir stabilitäts verluste und problme.
Wir sollten im moment alternativen suchen. ich werde auf jeden fall weiter arbeiten und es versuchen das 32bit problem zu beheben.
die Fehlermeldung ...

pi@pws-intercom ~ $ python testcall.py
Traceback (most recent call last):
File "testcall.py", line 1, in <module>
import linphone
File "/usr/local/lib/python2.7/dist-packages/linphone/__init__.py", line 1, in <module>
from linphone import *
ImportError: /usr/local/lib/python2.7/dist-packages/linphone/linphone.so: wrong ELF class: ELFCLASS6

**Comment by motom001** [comment]
Okay, ich hab hermanthegerman2 gebeten das Angebot vom Hersteller anzufordern. Auf Grundlage von dem Angebot kann dann entschieden werden wie es weiter geht.

**Comment by hermanthegerman2** [comment]
folgende Fragen stellt uns der Hersteller:

- what is the exact rasberry model you target to use --> raspberry pi model b, b+, ? (banana pi, pro?)
- what is the linux distribution you choosed to run on the rasberry ? --> rasbian (debian wheezy)
- do you need video support ? if yes, which codecs ? --> ??? H.263, H.264, MPEG-4 
- do you need software echo cancellation ? --> yes !

die Antworten hinter --> sind mein Vorschlag und jederzeit änderbar bzw. ergänzbar !

**Comment by pmunz** [comment]
Hallo

Ich würde einen Angaben voll zustimmen, aber je mehr
Modelle wir angeben desto mehr muss er Kompilieren, bzw coden für jedes Model eine eigene Version.
ich bin gerne bereit dafür etwas auszugeben aber ich glaube wir sollten uns auf ein Model beschränken .
Falls das ganze etwas Kostet wäre ich für Model B+

philipp
Philipp Munz. web/soft & Hardware Development. - Mac - Mobile - iPhone - Windows - 
Perfect Websolutions | Sinnhubstrasse 14 | 5020 Salzburg Austria 
Mobile: +43 (0) 676 9219693
For advertising - info, contact: our office | Twitter: click... | Visitenkarte zusenden

Am 23.01.2015 um 14:53 schrieb hermanthegerman2 <notifications@github.com>:

**Comment by motom001** [comment]
Die Frage für mich ist, was will der Hersteller mit diesen Fragen erreichen?

Wir benötigen den Python Wrapper für ARM 32-Bit - spielt die Hardware da eine so wichtige Rolle? Ist ARM 32- Bit nicht ARM 32-Bit?
Was für ein Unterschied macht die Distrubition?
Für das Angebot interessiert mich eine grobe Hausnummer der Gesamtsumme. Welcher Codec enthalten sein soll? Das richtet sich nach dem Preis...

Wenn das Gesamt-Angebot irgendwo bei 25 MT liegt, dann kann das eh keine Bezahlen.

Es geht dabei auch nicht um ein Angebot, dass auf den Cent genau sein muss, von mir aus soll er reinschreiben "Abrechnung nach tatsächlichem Aufwand", dann ist er auf der sicheren Seite.

Vielleicht ist Angebot auch die falsche Formulieren - vielleicht wäre Abschätzung besser...

**Comment by motom001** [comment]
um auch was produktives rein zu schreiben:
1. B+
2. Rasbian
3. H.264/MPEG4/MJPEG
4. ja, das ist meiner Meinung nach einer der Hauptaufgaben von einem sipphone

**Comment by pmunz** [comment]
Hallo Thomas.
ARM32 Bit ist schon Richtig nur die geräte haben verschidene Pocessoren .

**Comment by pmunz** [comment]
Bananapi 
ARM-Cortex-A7-CPU mit zwei Kernen / ARM-Cortex-A7-CPU mit vier Kernen
Raspberry
ARM1176JZF-S (700 MHz, ARMv6-Architektur, ARM11-Familie)
wobei beim raspberry der Boot vorgang in der Grafik GPU gemacht wird.

**Comment by hermanthegerman2** [comment]
OK, ich beantworte die Fragen mit:
1. B+
2. Rasbian
3. H.264/MPEG4/MJPEG
4. ja

**Comment by motom001** [comment]
Da zieht es mir die Schuhe aus:
http://www.linphone.org/news/32/26/Linphone-Python-for-Raspberry-Pi-3-8.html

Ich weiß was ich morgen abend mache... 
Danke @ linphone team!!! :-D

**Comment by motom001** [comment]
commit b8403a972a364463a7ec9383b5efc2c096461ca7

**Comment by motom001** [comment]
läuft bei mir als Teststellung - jetzt kommt es auf den Test bei Euch an
