### ISSUE TITLE
Probleme mit DoorPi / und SIP -Fone

### ISSUE THREAD

**Issue by coolhandx72** [motom001/DoorPi#182]
Hallo Ich versuche vergeblich mit meinem Raspi 3 und einer nagelneuen Fritzbox ein DoorPi zum laufen zubekommen, Nach 5 maliger Neuinstallation, hab auch schon einen lauffähige Kopie eines Kollegen benutzt und meine Daten eingetragen aber auch da bekomme ich keine Verbindung zwischen dem Pi und dem SIP Server, Pi läuft im Trace Modus - ich drücken auf dem Piface einen Klingelknopf --nichts-- ich versuche von einem Telefon den Pi anzurufen- keine Verbindung(im Display), und im trace sind immer wierder versuche vom Pi die Verbindung zum Fritzbox aufzubauen, erfolglos.
Die zweite Fritz hab ich aus dem Netzwerk elimniert, ich hab den doorpi nach der Anleitung im DoorPi Forum gemacht, ja ich weis hier wäre bestimmt eine bessere "grins" jeder mach mal Fehler.
https://www.doorpi.org/forum/thread/17-anleitung-pi2-jessie-release-2016-02-26-mittels-manueller-installation/
Schritt für schritt, leider Ohne Erfolg,  Vielleich hat mir euner von Euch nen guten Tipp wo das Problem liegen könnte, oder welche Anleitung gut funktioniert.
Gruß Arno 
 
[doorpi_kopie.zip](https://github.com/motom001/DoorPi/files/1910057/doorpi_kopie.zip)
[doorpi_trace.zip](https://github.com/motom001/DoorPi/files/1910058/doorpi_trace.zip)

**Comment by Schnup89** [comment]
Hi Arno,

auch wenn es etwas her ist, hast du evtl. einen Tippfehler bei der IP Adresse des Servers?

Linphone Server IP: 192.168.188.1
Pi IP: 192.168.0.10

**Comment by motom001** [comment]
bitte mal so testen: https://www.doorpi.org/forum/thread/1478-installation-mit-aktuellem-raspberryos/
