### ISSUE TITLE
Video-Support erbeten

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#22]
Bitte Video-Support hinzufügen. Es sollen PiCam oder Netzwerkkamera unterstützt werden.

**Comment by motom001** [comment]
Verbundene Issues:
#18 sipphone liblinphone einbinden
#50 sipphone empathy einbinden

**Comment by txgunman** [comment]
Hallo,
ich habe DoorPI auch ohne Probleme zum laufen bekommen und einfach gedacht das der Videostream mit motion einfach nebenher laufen kann. Das klappte leider nicht. Motion war installiert und lief, dann DoorPI hinterher und nur noch DoorPI(mit PiFace)ging.
Aber ich gebe nicht auf, das muss doch alles mit der im RPI forum genannten ELCOM App zum laufen zu bekommen sein...

**Comment by pancho01** [comment]
Hi,
ich klink mich hier mal ein. Um video-support zusammen mit der Elcom App zu bekommen muss man lediglich das paket mjpg-streamer installieren. Die Elcom App arbeitet mit jeder SIP Telefonanlage zusammen und unterstützt direkt MJPEG over http.
- Mjpegstreamer installieren
- Bsp für USB Webcam: starten mit mjpg_streamer -i "/usr/local/lib/input_uvc.so -d /dev/video0 -n -r 640x480 -f 15" -o "/usr/local/lib/output_http.so -n -w /usr/local/www -p 8080"
- und den stream im browser abgreifen http://raspiip:8080//?action=stream
- das selbe in der Elcom App eintragen unter Eingang & Kamera
  - Betriebsmodus: LBM/CBM-Module wählen
  - Video-URL:        http://raspiip:8080//?action=stream
  - SIP-ID Eingang: die SIP-ID Deiner Türsprechstelle

wenn nun der DoorPi die nummer deines PAd's anwählt erscheint auch der Stream :-) in der Elcom App

**Comment by txgunman** [comment]
Hi,
los gehts, wird getestet. Dann eben kein motion für's Bild.
Währe schön gewesen, wegen der Bewegungserkennung(zwei Fliegen eine Klappe...)
Den Trend zum "ZweitPi " einer für DoorPi einer für die Cam wollte ich vermeiden. Das geht aber dann ohne Probleme und das NAS wird mit DHL- und Postboten-Bilder nur so zugedonnert. I know, klingt ein wenig paranoid, aber man will ja nur die Technik testen :-). Wenn das Projekt steht gibts updates.

**Comment by motom001** [comment]
Ich bin aktuell noch dran liblinphone einzubinden, komme aber aktuell vor Lachen nicht dazu...
Das würde dann auch Video-Support bieten.

Wir sollten uns also Gedanken machen, wie die Rolle von DoorPi im Zusammenhang mit Motion / Aufzeichnung von Videos ist. Ist DoorPi zukünftig auch für die Koordinierung von Aufzeichnung und Bewegungserkennung zuständig oder nur Bild durchschleifen ab Klingeln?

**Comment by motom001** [comment]
Eine Lösung mit Elcom-App gibt es hier von pancho01, die zweite Lösung ist der linphone-Support (aktuell nur lokale Cams auf /dev/videoX). Wenn weiterer Bedarf besteht, dann bitte neuen Issue, sonst verliere ich den Überblick. Danke...

**Comment by thgorjup** [comment]
@pancho01: Wie kann ich realisieren, dass ich von der ELCOM auch den DoorPi anrufen kann?
Ich habe noch eine zweite, manuelle Klingel vor der Tür, die nicht am DoorPi angeschlossen ist. Also es klingelt dann autark und ich möchte dann den DoorPi vom ELCOM anrufen können.

**Comment by pancho01** [comment]
Hi thgorjup,
Du kannst in der Elcom App über das Kamera-Symbol eine Verbindung zum DoorPi aufbauen und damit z.B den Türöffner bedienen. Die Elcom App kann max 4 Aussenstellen verwalten die über die Kamera Icons auch manuell ausgewählt werden können.

**Comment by thgorjup** [comment]
Ok, danke. Werde ich ausprobieren.

Gruß
Thomas

Von meinem iPhone gesendet
