### ISSUE TITLE
DoorPi stoppt nachdem DTMF "#" gesendet wurde und SIPcall sofort beendet wurde

### ISSUE THREAD

**Issue by hermanthegerman2** [motom001/DoorPi#26]
Habe eben einen SipCall gemacht und nachdem DTMF "#" gesendet wurde und sofort danach aufgelegt wird läuft doorpi nicht mehr. Beendet man den SipCall erst nachdem das Event door-open abgearbeitet ist funktioniert doorpi weiterhin.

**Comment by motom001** [comment]
genau das sollte durch die Events nicht mehr passieren...

**Comment by hermanthegerman2** [comment]
was passiert bei Dir bei diesem Szenario? In den logs konnte ich nichts Auffälliges erkennen...

**Comment by hermanthegerman2** [comment]
erledigt mit:
https://github.com/motom001/DoorPi/blob/master/doorpi/action/handler.py#L185 
in folgende Zeile: 
__call__ = fire_event_asynchron

**Comment by motom001** [comment]
er macht voll den Issue zu... :-O
Ich mach den noch einmal kurz auf, damit ich die Lösung dokumentieren kann :)

**Comment by hermanthegerman2** [comment]
ich gelobe Besserung!

**Comment by motom001** [comment]
alles gut, das war mehr ein Scherz :)
