### ISSUE TITLE
Dashboard für den Webservice

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#27]
Es besteht der Wunsch, ein Dashboard für den Webservice anzubieten.
Die empfangenen Dateien sollen übersichtlich und strukturiert dargestellt werden.
Optional soll das Dashboard erweitert werden können.
Komponenten sind:
- DoorPi Allgemeiner Zustand
- Zustand und Konfiguration Inputs / Outputs
- Events und Actions
- Logdateien anzeigen
- Konfiguration anzeigen / bearbeiten (Drag&Drop?)
- ...

**Comment by motom001** [comment]
Vorab ist zu klären, ob dieses Webprojekt in diesem Projekt gepflegt wird oder doch zu DoorPiWeb ausgelagert wird? Thematisch hängen beide Themen zusammen, aber sie könnten auch unabhängig von einander laufen.
Was sagt Ihr?

**Comment by motom001** [comment]
Möglichkeiten:
##Webmin Modul (http://doxfer.webmin.com/Webmin/ModuleDevelopment)
## Vorteile
- unabhängig vom DoorPi und somit auch erreichbar wenn DoorPi eigentlich down ist
- starkes Admin-Werkzeug in das die Anzeige vom Status und die Konfiguration gut passen würde
##Nachteile
- mit Pearl würde eine neue Programmiersprache dazukommen
- benötigt zusätzliche Resourcen und Administration
##Dashboard im Webserver von DoorPi
## Vorteile
- Funktionsumfang gebunden an DoorPi Version und immer auf dem gleichen Stand
##Nachteile
- wenn DoorP down ist, dann ist keine Administration mehr möglich
##eigener Webserver (z.B. Apache oder lighttpd)
## Vorteile
- unabhängig vom DoorPi und somit auch erreichbar wenn DoorPi eigentlich down ist
- Entwicklung nicht an DoorPi gebunden
- vorgefertigte PHP-Frameworks können genutzt werden
##Nachteile
- benötigt zusätzliche Resourcen und Administration
- eventuell auch eine DB nötig?


Und jetzt Ihr, ich ergänze diesen Beitrag dann jeweils um die Vor- und Nachteile bis wir eine Entscheidung treffen können.

**Comment by hermanthegerman2** [comment]
Mein Wunsch: Dashboard im Webserver von DoorPi bzw. ausgelagert in DoorPiWeb

Vorteile:
benötigt zusätzliche Resourcen und Administration

**Comment by motom001** [comment]
Es ist jetzt so gelöst:
DoorPi startet einen Webserver
Wenn keine Konfiguration für den Webserver gefunden wird, dann:
- Port ist 80
- IP ist '' (an alle IP's gebunden)
- Benutzername und Passwort ist door / pi
- es gibt virtuelle und reale Resourcen:
-- virtuelle Resourcen sind z.B. /mirror und /status
-- reale Resourcen werden im Dateisystem gesucht und ggf. "geparst"
- sollten die realen Resourcen auf dem Pi nicht gefunden werden, wird automatisch zu einem "Online-Falback" geschwenkt und die Dateien von https://github.com/motom001/DoorPiWeb geladen

DoorPiWeb umfasst somit alle Resourcen wie das Dashboard etc.
Als Vorlage für das Dashboard kommt sb-admin-2 zum Einsatz
