### ISSUE TITLE
Loglevel (DEBUG, INFO, WARNING, ERROR) im doorpi.cfg einstellbar

### ISSUE THREAD

**Issue by hermanthegerman2** [motom001/DoorPi#34]
Wäre es möglich, die Loglevel im doorpi.cfg einstellbar zu machen.

Installation Loglevel --> DEBUG
Normalbetrieb --> WARNING, ERROR

**Comment by motom001** [comment]
Das Log-Level wird bereits beim Start (main.py) gesetzt.

Entweder es wird nur mit Info gestartet und ggf. später beim Einlesen der Config erweitert oder es wird mit Trace gestartet und ggf. später auf Info reduziert.

Andere Möglichkeit ist das Nutzen eines Parameters beim Start (z.B. --debug oder --trace) um das Log-Level bereits mit Start richtig zu setzen.
