### ISSUE TITLE
Clients (HTML+APP)

### ISSUE THREAD

**Issue by wuppi83** [motom001/DoorPi#35]
1. Anruf von 2 Geräten (zeitgleich) pro Input
2. SIP HTML Client ( vielleicht http://sipml5.org/)
3. Android / Iphone App

**Comment by hermanthegerman2** [comment]
zu 1. sollte bereits funktionieren: 
z.B:
[InputPins]
0 = call:**621,**623

**Comment by wuppi83** [comment]
[InputPins]
0 = call:**621,**610

Hatte ich versucht ... passiert leider gar nichts

**Comment by wuppi83** [comment]
klappt leider nicht ... hatte ich schon probiert

	-----Original-Nachricht----- 

	Betreff: Re: [DoorPi] SSH / Clients (HTML+APP) (#35) 

	Datum: Wed, 28 Jan 2015 19:36:09 +0100 

	Von: hermanthegerman2 <notifications@github.com> 

	An: motom001/DoorPi <DoorPi@noreply.github.com> 

	zu 1. sollte bereits funktionieren: 
 z.B:
 [InputPins]
 0 = call:621,623 

	—
Reply to this email directly or view it on GitHub [1].   

 Profitieren Sie von der sicheren E-Mail-Übertragung Ihrer Daten mit
einer kostenlosen E-Mail-Adresse der Telekom.
www.t-online.de/email-kostenlos

Links:
------
[1] https://github.com/motom001/DoorPi/issues/35#issuecomment-71889350

**Comment by motom001** [comment]
Essind ja mehrere Wünsche die Du hier ansprichst. Bitte in Zukunft pro Wunsch / Anforderung / Bug einen Issue eröffnen, sonst würd es unübersichtlich.
Den SSH-Wunsch trenne ich dann noch in einen anderen Isssue, die anderen kann ich versuchen hier zu beantworten.

Grundsätzlich stoßen wir dabei schon an die Abgrenzungen dieses Projektes. Aufgabe von DoorP ist nicht die Verwaltung aller internen Telefonnummern, sondern die Verbindung von Event zu Aktion. Ob die angerufene Nummer zu einem Gruppenanruf geht oder zu einer einzelnen Nummer ist DoorPi egal und es soll sich darum auch nicht kümmern. Das ist Aufgabe des SIP-Servers, der alle aktuellen Telefone kennt (die ggf. auch aktiv sind) und den Anruf als Parallelanruf oder stufenweise weiterleitet.

Eventuell stellt der SIP-Server Möglichkeiten zur Verfügung die dann genutzt werden können - z.B. es gibt bei der Fritzbox eine Möglichkeit (nennt sich Gruppenanruf) und würde so aussehen:
´´´
[InputPins]
0 = call:**611#612#613
´´´
http://avm.de/nc/service/fritzbox/fritzbox-7390/wissensdatenbank/publication/show/1148_Interne-Rufgruppe-in-FRITZ-Box-einrichten-Gruppenruf/

Ähnliches gilt für die Client-Seite. Ob es ein Handy, eine ISDN- oder DECT-Telefon, ein Tablet oder ein HTML-Client ist der den Anruf entgegennimmt soll DoorPi egal sein. Es ruft eine Nummer an und stellt die Verbindung her. Der Client ist ebenfalls nicht Bestandteil dieses Projektes.

Ob es irgendwann Projekte parallel zu DoorPi gibt, die genau diese Themen aufnehmen, will ich damit nicht ausschließen, aber im DoorPi Projekt ist es nicht geplant.

Anders ist es mit dem Wunsch "2.SSH Befehl für Türöffner über PiFace" - den hab ich als neuen Issue eröffnet.

**Comment by wuppi83** [comment]
Moin Motom001,

danke für deine Rückmeldungen. Mit dem Gruppenruf will ich nur erreich, dass ich das gespräch an jedem Tablet und zusätzlich an den festnetztelefonen annehmen kann. Danke dafür ... werde ich nachher gleich testen.

das mit dem Client dachte ich, ist auch in Planung ... na vielleicht findest sich dafür noch jemand. Cool wäre es nämlich, wenn wer klingelt und ich bin nicht zu hause, dass das ganze dann auf mein Handy weitergeleitet wird.

**Comment by pmunz** [comment]
Lade dir auf dein Handy einen SIP Client , zB linphone , den kannst du über die VoIP tk anbinden und telefonieren , oder du öffnest deine Firewall , dynamische ip kannst du über noip.com Regeln . Lg Philipp

**Comment by pmunz** [comment]
Sorry no-ip.com

**Comment by motom001** [comment]
@wuppi83: Ich weiß was Du erreichen willst, ist bei mir ja ähnlich. Auch ich möchte einen Anruf auf meinem Handy, wenn ich nach 15 Sekunden am Festnetz nicht rangegangen bin. Aber das habe ich nicht im DoorPi umgesetzt, da es dort nicht hingehört. Das gehört in den SIP-Server eine solche Logik abzubilden.

An der Beschreibung von pmunz siehst Du schon, wie umfangreich das Thema ist / werden kann. 

An der Stelle muss ich, als aktuell einziger Entwickler von DoorPi, leider die Segel streichen und auf bestehende Komponenten verweisen. Ein Anruf von DoorPi zum SIP-Server und der managt den Rest (dafür, und genau dafür, ist der SIP-Server ja auch da). Dann ist es DoorPi egal ob Parallelanruf, Callthrough, Rufsperren oder sonst was gewünscht ist.

**Comment by motom001** [comment]
Ich schließe den Issue  - hier kann, auch wenn geschlossen, gern über das Thema weiter diskutiert werden. Sollte sich doch rausstellen, dass ich vollkommen falsch liege, öffne ich den Issue auch gerne wieder - Okay?
