### ISSUE TITLE
SSH Befehl für Türöffner über PiFace

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#36]
Stammt aus Issue #35 "SSH / Clients (HTML+APP)"

Wunsch / Anforderung:
SSH Befehl für Türöffner über PiFace

**Comment by motom001** [comment]
Ich brauche dazu eine Beschreibung, was soll der Auslöser für das event sein?

**Comment by wuppi83** [comment]
Ich möchte gerne in IP-Symcon das Event durch das auslösen eines Buttons triggern. Im Grunde brauche ich daher nur den ssh befehl. Das Script für IP Symcon würde ich dann schreiben und einstellen.

**Comment by wuppi83** [comment]
dachte ich kann das über ein Python Script steuern

#!/usr/bin/python

from time import sleep
import piface.pfio as pfio
pfio.init()
pfio.digital_write(0,1) #turn on
sleep(3.0)
pfio.digital_write(0,0) #turn off
exit()

Klappt aber so leider nicht.

**Comment by motom001** [comment]
Es gibt aktuell keine Möglichkeit per SSH den Türöffner zu betätigen wenn DoorPi läuft.
Wenn der Ausgang am PiFace durch DoorPi geblockt ist, kommt man mit externen Programmen dort nicht mehr ran.
Wenn man mit einem externen Script z.B. pfio.init() ausführt, nimmt man DoorPi im laufenden Betrieb die Verbindung zum PiFace weg.
Somit muss eine andere Schnittstelle gefunden werden. Deshalb frag ich ja, wie dieser ssh-Befehl aussieht. Und muss es unbedingt ein ssh-Befehl sein oder gibt es auch andere Möglichkeiten (Webservice, ...)?

**Comment by wuppi83** [comment]
SSH Befehl hatte ich nur gedacht, weil ich mir da selbst ein Script bauen hätte können ;0) Es wäre aber schon cool wenn wir in IPS das Relais ansteuern könnten. Vielleicht ja ja Hermann mal wieder ne Idee ?! ;0)

**Comment by hermanthegerman2** [comment]
@motom001 
Lässt sich Doorpi evtl. auch anrufen ? Geht das programmiertechnisch überhaupt ?
Falls ja könnte man von IPS aus über DTMF kommunizieren und Events auslösen.

**Comment by pmunz** [comment]
ja du kannst DoorPi anrufen ! in der dorrbi.cfg das entsprechende Telefon / Sip Client unter Admin Modus eintragen. den Sip Server gegebenenfalls auf autoawnser Stellen.

**Comment by hermanthegerman2** [comment]
wenn das geht ist das "Problem" bereits gelöst !

**Comment by wuppi83** [comment]
@  hermanthegerman2 

teste ich :0)

**Comment by hermanthegerman2** [comment]
Super danke!

**Comment by motom001** [comment]
Ansonsten Merker für mich:
InputEmulator auf /tmp/doorpi/Input/Emulator/x
OuputEmulator auf /tmp/doorpi/Output/Emulator/x
FileSystemWatch ähnliche, eventgesteuerte Abfrage auf den Input-Ordner und Konfigurationserweiterung unter Inputs (Keyboard-Splitting in Input und Output vorausgesetzt)

**Comment by wuppi83** [comment]
Habe das Script fertig, leider wird die Raute für den Türöffner nicht genommen ?!
Stelle das heute abend mal ein. Vielleicht hat einer ne Idee von euch.

**Comment by pmunz** [comment]
Hallo, welchen SIP- Server / Hardware nutzt Du ? der Hash ist oft Reserviert und kann dadurch nicht verwendet werden, ansonst versuch mal an deinem Client den Ton den der Hash ausgiebt um paar millisekunden zu verlängern. Funktionieren andere DTMF töne ?
LG Philipp

**Comment by wuppi83** [comment]
Hallo ich habe ne Fritzbox 7390 ? Script habe ich ebend mal gepostet

http://www.ip-symcon.de/forum/threads/26739-DoorPI-VoIP-Door-Intercomstation-with-Raspberry-Pi?p=246420#post246420

**Comment by hermanthegerman2** [comment]
Evtl. könnte man Modbus in Verbund mit #45 für diese Anforderung verwenden:
http://www.ip-symcon.de/forum/threads/21088-Raspberry-PI-Modbus-TCP-IP-Server?highlight=raspberry+modbus

**Comment by motom001** [comment]
@wuppi83: Hilft dir der letzte commit mit dem Filesystem-Keyboard oder fehlt noch mehr?
https://github.com/motom001/DoorPi/commit/c671b5c752bb6c12c41ff62084b0a9a688efa293

**Comment by motom001** [comment]
andersrum gesprochen - per SSH lässt es sich jetzt steuern, der Rest kommt mit einem passenden Webservice unter #57
