### ISSUE TITLE
Readme und Wiki überarbeiten

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#43]
Ich brauche echt Hilfe beim Überarbeiten von Readme und Wiki. Das kostet so viel Zeit und stimmt mit jedem commit weniger zum aktuellen Stand.

Wer kann mir helfen, Struktur und Inhalte der Dokumentationen auf einen aktuellen Stand zu heben?

**Comment by Schwa-l-be** [comment]
kann dir gerne helfen. welche Teile sollten denn im speziell zuerst überarbeitet werden?

**Comment by motom001** [comment]
Eigentlich einmal alles und zwar so, dass es nicht nur der Entwickler versteht.
1. Die Readme.md sollte überarbeitet werden und das Projekt beschreiben und nicht meine Umgebung zu Hause. 
2. Die Installationsanleitung sollte zweisprachig vorhanden und auf einem aktuellen Stand sein.
3. Die Ersteinrichtung sollte genauer beschrieben sein.
4. Und die Konfigurationsmöglichkeiten besser / überhaupt beschrieben werden.
5. Zu Schluss noch eine FAQ aus den Issues die mit FAQ markiert sind - kurz Problem (Fehlermeldung) und Lösung dazu.

DoorPi ermöglicht mit der Config-Datei so viel, aber nur ein Bruchteil ist beschrieben und aktuell.
Wenn ich die Doku schreibe, dann verstehe ich es - aber in einigen Fällen kein Anderer.

Wenn die Readme fertig wäre, dann würde ich daraus gern eine Seite erzeugen lassen (https://pages.github.com/) und dort versuchen es übersichtlich zu gestalten.

**Comment by Schwa-l-be** [comment]
https://github.com/Schwa-l-be/DoorPi/wiki/Installation-DE

ein Vorschlag zur Installationsanleitung auf Deutsch.
Sollte das ganze noch ausführlicher sein oder ist das ok?

**Comment by pmunz** [comment]
Du musst noch ein chmod +x doorpi.sh setzen 
Sonst kannst du es nicht ausführen 

Lg


Philipp Munz. web/soft & Hardware Development. - Mac - Mobile - iPhone - Windows - 
Perfect Websolutions | Sinnhubstrasse 14 | 5020 Salzburg Austria 
Mobile: +43 (0) 676 9219693
For advertising - info, contact: our office | Twitter: click... | Download Mail Public Keys

**Comment by Schwa-l-be** [comment]
geändert.

Sollt DoorPi wie im Skript unter /home/DoorPI installiert werden oder wie zu Beginn oder /home/pi/DoorPi?

**Comment by motom001** [comment]
WOW - ich bekomme die Kinnlade nicht mehr zu. Wie lange war ich weg?
Super Leistung!

**Comment by motom001** [comment]
@Schwa-l-be Kannst Du mir bitte eine Mail an motom001@gmail.com schicken? Danke...

**Comment by pmunz** [comment]
Hallo , vielleicht könnte am in das Installations Todo noch optional den download aus der konsole anbiten, somit fält FTP uns sonstiges flach.

wget http://raspberrypi.roxxs.org/EPSPi/packs/DoorPI.sh

**Comment by Schwa-l-be** [comment]
Bezüglich der config Datei: wird sich nach Umsetzung von issue #54 viel ändern, so dass es sich lohnt zu warten oder bleibt der Großteil gleich?

**Comment by motom001** [comment]
Inhaltlich bleibt alles gleich. Problem aktuell ist, dass die Leute die fertige cfg nicht anpassen und dann sich fragen, warum es nicht geht. Deshalb soll die cfg gelöscht werden und es werden demo.cfg bereit gestellt. Aus den ganzen Demo-cfg kann sich dann jeder seine eigene cfg zusammenbauen.
Also bleibt die cfg inhaltlich gleich, sowohl Aufbau als auch Parameter. Somit kann auch die Doku dafür gleich bleiben, es kommt nur der Hinweis auf die Demo-cfgs dazu.
Oder stellen wir die demo-Konfigurationen komplett nur ins Wiki und man muss die sich dann von dort rauskopieren?

**Comment by Schwa-l-be** [comment]
Ich hoffe ja mal dass die Leute die DoorPi installieren wollen das Wiki auch lesen und somit sollte es meiner Meinung ausreichen, dort die Demo-Konfig zu beschreiben.
Dadurch dass sie sich bereits beim konfigurieren mit dem Wiki auseinander setzen, könnte helfen, dass auch das FAQ benutzt wird bevor gefragt wird.

**Comment by motom001** [comment]
Und das aufs Wiki verwiesen wird, kann ich im Quellcode mit entsprechenden Fehlermeldungen verankern. So sollte es klappen... (#56)

**Comment by Schwa-l-be** [comment]
Jetzt muss ich mal nachfragen... 
Wollte gerade am Konfig Wiki was tun aber versteh die virtuelle Tastatur nicht :D 
Wenn ich jetzt Pin 5 für 3 Sekunden schalten will wie muss ich das dann definieren?

**Comment by msmolny** [comment]
Du musst einen einen passenden OutputPin definiere, z.B.

    [boardgpio_OutputPins]
    5 = Tueroeffner

und dann mit einer aktion diesen Pin zuerst auf 1 und dann auf 0 schalten, mit Verzögerung 3

    ... = out:Tueroeffner,1,0,3

Das kann passieren als DTMF Aktion

    [DTMF]
    "#" = out:Tueroeffner,1,0,3

aber genauso auf Knopfdruck eines Input Pins eines anderen keyboars

    [rfidreader_InputPins]
    1234567 = out:Tueroeffner,1,0,3


Zur Vollständigkeit halber noch meine Keyboard Definitionen

    [keyboards]
    boardgpio = gpio
    rfidreader = rdm6300

**Comment by Schwa-l-be** [comment]
soweit klar nur wie sieht das ganze dann mit SSH Befehl aus wie in #36 ?
Also ich frag mich wie ich das damit anspreche

**Comment by msmolny** [comment]
Ach so, verstehe. Sorry, kenne die Historie aus #36 nicht so gut, aber nach dem, was ich gelesen habe, ist die Idee:

    [keyboards]
    virtuell = filesystem

    #======== Config for Filesystem Keyboard =========
    [virtuell_keyboard]
    reset_input = true
    base_path_input = /var/DoorPI/keyboard/inputs/
    base_path_output = /var/DoorPI/keyboard/outputs/

    [virtuell_InputPins]
    tueroeffnertaste = out:Tueroeffner,1,0,3

und man muss den türöffnern mit folgendem Shell-Befehl über SSH betätigen:

    echo 1 > /var/DoorPI/keyboard/inputs/tueroeffnertaste

**Comment by motom001** [comment]
Ist so vollkommen richtig...

**Comment by pistreamer** [comment]
Bezüglich Wiki, sollte unbedingt eine Anleitung bezüglich Absicherung (User/Group) vom Webinterface rein.

---> von motom001 gepostet am http://www.forum-raspberrypi.de:
Wenn es um eine Weboberfläche geht, dann sollte diese auch abgesichert sein.
Dazu gibt es Nutzer (User) die in Gruppen (Groups) zusammengefasst sind.
Diesen Groups sind  Bereiche (AREA) zugeteilt, die lesend oder schreibend genutzt werden können.
Die Bereiche (AREA) sind virtuelle und reale Ressourcen, die sich speziell an der URL unterscheiden (daher kam auch die Idee es in Bereiche einzuteilen). 
Die Bestandteile eines Bereiches werden mittels RegEx definiert.

Zuordnung in der Sektion User ist:
[Benutzername] = [Passwort]

Bei der Group Sektion ist es:
[GroupName] = [Benutzername1],[Benutzername2],[...]

Dann gibt es die beiden Sektionen WritePermission und ReadPermission mit der Zuordnung:
[GroupName] = [AreaName]

Ganz unten gibt es dann beliebig viele Areas mit unterschiedlichen Namen. Jeder Area sind RegEx zugeordnet, die gegen die URL geprüft werden.
Eine Sonderform ist die AREA_public. Diese fasst alle Ressourcen zusammen, die von jedem eingesehen werden dürfen, da es sich hierbei um Javascript,CSS und ähnliche Dateien handelt.
Nötig wurde das, da die login.html auch Javascript-Dateien geladen hatte. Mitlerweile habe ich mich von der login.html einw enig verabschiedet und bin Richtung HTTP Status-Code 401 mit base64 codiertem Benutzername/Passwort gegangen. Das lässt sich später auch automatisch durchführen, so dass Webservice-Aktionen mit Authentifizierung auf einem sehr einfachen standardisierten Level möglich sind.

Ist bestimmt nicht einfach meinen Quatsch-Gedanken zu folgen, zumal viel Salitos geflossen ist, während ich programmiere. Aber dafür klappt es ganz gut Icon_smile

Beispiel:

Code: Alles markieren
[User]
moto = moto
doorpiweb = doorpiweb
visitor = visitor
door = pi

[Group]
administrator = doorpiweb,motom001,moto,door
visitors = visitor

[WritePermission]
administrator = dashboard,status,config

[ReadPermission]
visitors = dashboard

[AREA_config]
/control/config_value_get
/control/config_value_set
/control/config_value_delete
/control/config_save
/control/config_get_configfile

[AREA_status]
/status
/mirror

[AREA_dashboard]
/dashboard/pages/.*html

[AREA_public]
/dashboard/bower_components/.*
/dashboard/dist/.*
/dashboard/js/.*
/dashboard/less/.*
/login.html
/favicon.ico

**Comment by motom001** [comment]
Das Wiki kann jeder bearbeiten - kannste gern mit einfügen - wäre sogar sehr froh drüber.
Allerdings ist das eben noch nicht 100% fertig - ob Read und Write bleibt, weiß ich noch nicht.

**Comment by pistreamer** [comment]
Wollte die wiki Seite gerade updaten jedoch habe ich anscheinend keine Schreibrechte zum pushen..
git-receive-pack not permitted

**Comment by pistreamer** [comment]
Na endlich habee ich einen edit Button im Wiki ... wurde aktualisiert...
