### ISSUE TITLE
Update-Routine für DoorPI

### ISSUE THREAD

**Issue by wuppi83** [motom001/DoorPi#54]
Ich hatte gerade das Problem das sich ja die pjsua ja in den letzen zwei Tagen geändert hat.
Der Befehl "sudo git pull" konnte mein Problem jedoch nicht lösen. Ich musste daher DoorPI neu installieren. Eine Update-Routine wäre daher super. 

PS: Ohne die Hilfe von Hermann hätte ich das natürlich wieder nicht hinbekommen !!!

**Comment by motom001** [comment]
Kann dafür nicht theoretisch das Install-Script genutzt werden? Im schlimmsten Fall ist es zwei mal auf der SD-Karte vorhanden.

Abgesehen davon würde es vermutlich auch mit pjsip 2.1 funktionieren.

**Comment by motom001** [comment]
@hermanthegerman2 Wie habt Ihr es jetzt gelöst?

**Comment by hermanthegerman2** [comment]
Hardcore Variante! 
DoorPI gelöscht und neu mit git clone gezogen.
Hätte es evtl. nicht gebraucht allerdings ging es so für wuppi83 leichter.

Ich werde es selbst mal testen, wenn es wieder umfangreichere Änderungen am Code gibt.

**Comment by motom001** [comment]
Ähnlichen Weg könnte auch ein Update-Pfad mit dem DoorPi Installer sein -> einmal den Ordner löschen, neu installieren.
Allerdings bin ich mir beim pjsip nicht sicher - das wird nicht von der Version her geprüft sondern nur ob es überhaupt vorhanden ist. Eventuell müsste da noch einmal angesetzt werden.

**Comment by wuppi83** [comment]
Wäre eine Variante... aber dann wäre die config weg ... uns das wäre ja auch doof.

**Comment by motom001** [comment]
sollte bald der Vergangenheit angehören, da die cfg und ini verschwindet.
Zukünftig wird es dort nur noch *.demo.cfg Dateien geben, die zusammengesetzt werden können zu einer cfg. Dadurch würde die cfg nicht neu von github geladen und beim Update auch nicht überschrieben.
Geplant sind:
RPi_GPIO.demo.cfg
pjsua.demo.cfg
RPi_PiFace.demo.cfg
recorder.demo.cfg
player.demo.cfg
smtp.demo.cfg
events.demo.cfg
doorpi.demo.cfg

Hab ich was vergessen?

**Comment by hermanthegerman2** [comment]
Wahnsinn was momentan abgeht …

 

IP-Symcon.demo.cfg

 

Von: Thomas [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. Februar 2015 10:28
An: motom001/DoorPi
Cc: hermanthegerman2
Betreff: Re: [DoorPi] Update-Routine für DoorPI (#54)

 

sollte bald der Vergangenheit angehören, da die cfg und ini verschwindet.
Zukünftig wird es dort nur noch *.demo.cfg Dateien geben, die zusammengesetzt werden können zu einer cfg. Dadurch würde die cfg nicht neu von github geladen und beim Update auch nicht überschrieben.
Geplant sind:
RPi_GPIO.demo.cfg
pjsua.demo.cfg
RPi_PiFace.demo.cfg
recorder.demo.cfg
player.demo.cfg
smtp.demo.cfg
events.demo.cfg
doorpi.demo.cfg

Hab ich was vergessen?

**Comment by motom001** [comment]
cfg ist weg - Doku wesentlich verbessert - ich schließe den Issue hier, denn ein Update von DoorPi ist mittels `git pull` möglich und sicher.
