### ISSUE TITLE
webservice with authentication to trigger actions

### ISSUE THREAD

**Issue by miyorni** [motom001/DoorPi#57]
great Job !! 
I have doorpi up&running and it is working like a charm . 
one feature that would be really nice would be a webservice  event source . 
I was thinking of tornado non blocking http server python library .
http://tornado.readthedocs.org/en/stable/
I tried to implement it my self but my programing skills are quiet limited .

this would allow access the internals event (open door,lights ...) from other applications as the GPIO are locked by the doorpi deamon .

Bernardo

**Comment by motom001** [comment]
What will be the main advantage of this webservice?
One way to forward the events will you find in this example:
https://github.com/motom001/DoorPi/blob/master/doorpi/action/SingleActions/ipsrpc_setvalue.py

If you tell us more about your target, we will find a way to solve it.

**Comment by miyorni** [comment]
Actually the target is doorpi itself . the event I want to trigger are the internal ones (out,call,mailto ... )
basically when requesting a specific URL  ex "/page1" trigger action  out:Tueroeffner,1,0,3 . 
this would allow us to access doorpi as a gateway for other applications (in my case openremote) .
ideally this could be a REST Web service with some kind of security (token, user/pass) .

[WEBSERVICE]
port=8082
key="123443324453445"
"/" = out:Tueroeffner,1,0,3
"/page1" = out:Stromversorgung,0
"/index.html" = out:Stromversorgung,1

so for example:
http://doorpi/page1&key=123443324453445      
would trigger  -->  out:Stromversorgung,0

what do you think ? 

Bernardo

**Comment by motom001** [comment]
Duplicate to #36 
Reference to #45 

okay - second request in the same direction.
I will see what I can do for you.

**Comment by motom001** [comment]
I hope it's okay for you, when I change the issue title.

**Comment by miyorni** [comment]
this sounds good for me . 
thx

**Comment by motom001** [comment]
first step is done:
webservice with authentication

next step is dashboard to show the current doorpi status and control of e.g. keyboard

**Comment by motom001** [comment]
Zitat aus einem Forum:

>So, da es alle drei Themen betrifft - Events aus der Weboberfläche abfeuern geht jetzt.
>Damit kann 
>- das Fremdsystem das Event auslösen @emilio20
>- aus der Ferne die Klingel gedrückt werden @Slim80
>
>Nur die Syntax der URL hat sich etwas geändert:
>http://192.168.178.43/control/trigger_event?>event_name=OnKeyPressed_testsystem.11&event_source=keyboard.from_gpio
>
>Damit man sich das nicht immer selbst zusammenbauen muss, gibt es in der Weboberfläche das >bereits vorbereitet:
>http://192.168.178.43/dashboard/pages/status.modules.eventhandler.html
>
>Dort sieht man zwei Register. Das Zweite "Quelle - Event" zeigt alle Quellen und deren gespeicherte Events.
>In der Spalte Eventname ist ein Button, dessen URL auf genau die passende Webservice-URL zeigt.
>Wenn der Button gedrückt wird, dann reagiert ein onclick Event und zeigt als Modal-Dialog das Ergebnis an.
>Man kann aber natürlich die URL kopieren und im Fremdsystem einrichten.
>
>Wie gesagt, Authentifizierung würde klappen mit:
>http://door:pi@192.168.178.43/dashboard/pages/status.modules.eventhandler.html
>
>
>PS: Gab noch ein kleinen Schönheitsfehler im Webservice, deshalb ein Update für DoorPi - ist aber optional, die neuen Funktionen klappen auch so:
>https://github.com/motom001/DoorPi/commit/c3615177b3d6df35cc23fdf29e28b321d2874be7
>
>Wer den OnlineFallback nutzt (also alle ohne lokale DoorPiWeb), können einfach die Seite im Dashboard aufrufen und bekommen die Button angezeigt.
>Alle die es loakl haben wollen, müssen DoorPiWeb aktualisieren:
>https://github.com/motom001/DoorPiWeb/commit/b23bc6eacabeef8e9326dd64a3d794c7be61d7ef


Quelle: http://www.forum-raspberrypi.de/Thread-haussteuerung-doorpi-voip-wechselsprechanlage-tuersprechanlage-mit-video-support?pid=170620#pid170620

Damit sehe ich das Thema erst einmal als erledigt an - oder?
