### ISSUE TITLE
Adding any Features

### ISSUE THREAD

**Issue by svalcken** [motom001/DoorPi#60]
Hello,

here my idea's:
Adding videostreaming support
Adding compatibility for Synology Survival Server (video recording)
Adding audio recording in the videostreaming
Adding event channels support for detection of Alerts like door belling, sabotage, motion detection
Adding control based on temperatur for a heating element (outdoor installation)
Adding a eventcontrol for a postbox (Send a E-Mail, SMS or another if post is delivered)
Adding a control for disable the door belling (Timebased/Eventbased (Like a switch). (I have not checked if exists in the project)

If this integrated, i will build my own DoorPi.

Great Job.
Thanks

**Comment by motom001** [comment]
>Adding videostreaming support

see #22 and milestone 3.0 (https://github.com/motom001/DoorPi/milestones/v3.0)

>Adding compatibility for Synology Survival Server (video recording)

first we need video-support before we could record it

>Adding audio recording in the videostreaming

of course, when we have video-support

>Adding event channels support for detection of Alerts like door belling, sabotage, motion detection

What do you want to do? I think the most cases are possible with the current version.

>Adding control based on temperatur for a heating element (outdoor installation)

This sounds interessting, but I can't see the where it could relevant to doorpi. Please explain your plan.

>Adding a eventcontrol for a postbox (Send a E-Mail, SMS or another if post is delivered)

E-Mail is possible when you could offer a sensor. Maybe a sensor at the postbox flap?  
SMS is a nice idea for further development.
And what do you mean with "or another"?

>Adding a control for disable the door belling (Timebased/Eventbased (Like a switch). (I have not checked if exists in the project)

Today it is possible with cronjob to start and stop doorpi. How do you want this feature? Please explain it a little bit more.
