### ISSUE TITLE
Fehler beim Beenden eines Gesprächs

### ISSUE THREAD

**Issue by frrr1** [motom001/DoorPi#63]
Beim Ablehnen des Gespräches auf meinem SIP Handy tritt bei mir folgender Fehler

2015-03-11 21:46:50,408 [DEBUG]         [action.handler] fire for event OnCallStateDisconnect this actions [<action.base.SingleAction instance at 0xf90418>, <action.base.SingleAction instance at 0xf903a0>]
python2: ../src/pjmedia/conference.c:1018: pjmedia_conf_disconnect_port: Assertion `conf && src_slot<conf->max_ports && sink_slot<conf->max_ports' failed.

auf.

Ich beschäftige mich seit kurzem mit DoorPi und möchte künftig auch etwas dazu beitragen. Allerdings muss ich gestehen, dass ich mit python schon lange nichts zu tun hatte...

Bezgl. des Fehlers können wir uns evtl. per Mail unterhalten? Ich hätte auch ein paar grundsätzliche Fragen zur Entwicklung(sumgebung).

**Comment by frrr1** [comment]
Evtl. kann die Ursache dafür sein, dass >>self.call.info().conf_slot<< (Wert zur Laufzeit -1) noch nicht initialisiert ist. Aber andererseits gehe ich davon aus, dass das Ablehnen eines Gesprächs sicher schon getestet wurde...

**Comment by frrr1** [comment]
Folgender Code im SipPhoneCallCallBack.py hat bei mir geholfen:


if self.call.info().state == pj.CallState.DISCONNECTED:

            call_slot = self.call.info().conf_slot

            if call_slot > -1:
                DoorPi().event_handler('OnCallStateDisconnect', __name__, {
                    'remote_uri': self.call.info().remote_uri
                })
                self.Lib.conf_disconnect(call_slot, 0)
                self.Lib.conf_disconnect(0, call_slot)
                logger.debug("disconneted Media from call_slot %s",str(call_slot))
                DoorPi().event_handler('AfterCallStateDisconnect', __name__, {
                    'remote_uri': self.call.info().remote_uri
                })
            else:
                DoorPi().event_handler('OnCallStateDismissed', __name__, {
                    'remote_uri': self.call.info().remote_uri
                })

Wäre das nur Symptombekämpfung? Gibt es bessere Ansätze?

**Comment by motom001** [comment]
*ThumbsUp*
Wäre das jetzt ein PullRequest, würde ich dem zustimmen :)
Normalerweise wird von mir ein kurze Checkliste mit kleinen Tests durchgegangen. Da ist auch "Anruf abweisen" mit beinhaltet. Allerdings kann ich nicht ausschließen, dass ich nach dem vierten Salitos einen Fehler gemacht habe...
