### ISSUE TITLE
DoorPi: Dokumentation vs. Version & Webserver & Service läuft nicht 

### ISSUE THREAD

**Issue by pawart** [motom001/DoorPi#64]
Hi Thomas und Kollegen,

Zuerst mal Jubel, Lob Respekt. 
Das ist im Prinzip genau die Basis nach der ich gesucht habe 
muss das jetzt nur noch um ein paar dinge erweitern.

* SOBALD die BASIS ES GEHT* :)

Und da hab ich derzeit noch ein paar Hickups:

(1) hab euer Installer script verwendet wie beschrieben, die config editiert - bekomme aber 
==> KEINEN laufende webserver auf port 8080 
==> auch nach neustart lauft ein service - auch wenn ich es  manuell starte tut sich da nix. (ps aux | grep DoorPi  
(2) hab das DoorPiWeb gecloned un versucht es zu starten tut auch nicht das was ich mir dachte.

 sudo service doorpi start
Starting server

    ___                  ___ _
   /   \___   ___  _ __ / _ (_)  VoIP Door-Intercomstation with Raspberry Pi
  / /\ / _ \ / _ \| '__/ /_)/ |  version:   2.0 #57
 / /_// (_) | (_) | | / ___/| |  license:   CC BY-NC 4.0, 2014-2015
/___,' \___/ \___/|_| \/    |_|  URL:       <https://github.com/motom001/DoorPi>

...
2015-03-15 07:08:23,101 [INFO]          [__main__] loaded with arguments: ['/home/DoorPI/doorpi/main.py', 'start', '--configfile', '/home/DoorPI/conf/doorpi.cfg']

pi@raspberrypi ~ $ ps aux | grep doorpi
pi        1526  0.0  0.4   4100  1816 pts/0    S+   07:09   0:00 grep --color=auto doorpi

==> Wie starte ich die webseite? (als Service? bei bedarf ...?)

* Wird eigentlich der Terratec Aureon DualUSB  Audio Stick unterstützt?
* hagenuk VoipTel 40?
* Voip Buster als SIP Server?

Welche Doku könnt ihr mir noch empfehlen?

Danke!

P.

**Comment by Schwa-l-be** [comment]
Anscheinend wird deine Soundkarte am Pi unterstützt und funktioniert somit auch mit DoorPi.
Das VoipTel ist ein USB Voip Telefon. Willst du es direkt am Pi benutzen oder wird es nur am PC betrieben und am SIP Server betrieben?
Welchen SIP Server du verwendest ist eigentlich egal. Ich hab mal nachgeschaut und VoIP Buster sieht für mich eher nach VoIP Anbieter anstatt nach Server aus lasse mich aber gerne eines besser belehren.

Bezüglich Konfigration: ich bin gerade dabei dazu die Doku zu erstellen hab im Moment noch ein Problem bei meiner Config.. Die aktuelle config Datei sollte dir aber Aufschluss geben.

Gruß 
Dennis

**Comment by pawart** [comment]
Hallo!

(1) Die Soundkarte / USB Stick hat vermutlich eine zu große Stromaufnahme ODER mein 5V/2A Netzteil schaft das nicht  zusammen mit dem WLAN Dongle der ja auch noch am USB angesteckt ist.

(2) ich wollte das Telefon direkt verwenden um als Gegensprechanlage zu dienen:
Es hat ein Keypad, einen grünen knopf, roten knopf und ein display. Vom stromverbrauch ist es auch viel besser und ich kann es paralell anstecken. Gekostet hat es vor 5 Jahren mal 9€. 

(3) ich hab kein Problem mit den Kosten, ich möchte nur dass es auf meinem Normalen Handy leutet - und da fallen so oder so dann irgend wo kosten an oder? 
UND: ich erspar mir einen eigenen SIP Server, den ich ja auch noch betreiben müßte

(4) Dokumetation: Da warte ich ganz gespannt. wann schätzt du das du die soweit fertig hast? 
DANKE!

LgP

**Comment by motom001** [comment]
zu 1.
Hab auch Dongle und Sound-Karte am Pi hängen und es klappt trotzdem alles. Sicher das es das ist?

zu 2.
Telefon direkt verwenden? Es muss per USB angeschlossen werden - und da stellt sich die Frage wo Du es anschließen willst. Am PC?

zu 3.
UND Du machst Dich abhängig von Deiner Internetanbindung. Ist die "tot", dann klingelt gar nichts.

zu 4.
Doku ist eine never ending story und ich bin so froh, dass Schwa-l-be da mit anpackt.
Wenn du uns sagst, welche Doku noch benötigt wird, dann könnte man genau verstehen ob und wo noch was fehlt.

**Comment by motom001** [comment]
Sind noch fragen offen, dann Issue bitte wieder öffnen. Ich schließe den erst einmal um wieder mehr Übersicht zu bekommen.
