### ISSUE TITLE
OpenHAB Integration

### ISSUE THREAD

**Issue by frrr1** [motom001/DoorPi#67]
OpenHAB ist ein System welches verschiedenste Systeme miteinander kommunizieren lässt. Darunter, als wichtigster Bestandteil, KNX zur Hausautomatisierung.

Anwendungsfall, den man mit einer Integration z.B. umsetzen könnte:
Wenn der Besucher läutet soll automatisch ein KNX Telegramm gesendet werden, welches das Licht im Eingangsbereich einschaltet.

**Comment by motom001** [comment]
Klingt nach ähnlicher Anforderung wie #31 
Eventuell können Datei als Vorlage genutzt werden:
https://github.com/motom001/DoorPi/blob/master/doorpi/action/SingleActions/ipsrpc_setvalue.py
https://github.com/motom001/DoorPi/blob/master/doorpi/action/SingleActions/ipsrpc_call_value.py

Da ich das System nicht kenne müsste ich wissen welche Methoden der API angesprochen werden sollen. Anders gesprochen - was soll genau im OpenHAB passieren / gemacht werden?

**Comment by Schwa-l-be** [comment]
seit DoorPi bei mir wieder läuft hab ich es mit meiner Mini OpenHAB Installation verbunden um ein Licht zu schalten wenn es klingelt das mach ich über die URL: http://<openhab-host>:8080/CMD?<item>=<state> die von OpenHAB geboten wird.

[EVENT_OnKeyPressed]
10 = os_execute: wget -O - -q 'http://192.168.178.29:8080/CMD?Keller-Klingel=ON

das ganz hängt dann noch mit Regeln in OpenHAB zusammen, die nur das Licht schalten, falls jemand anwesend ist und es nach 10 Sekunden auch wieder abschalten

**Comment by frrr1** [comment]
Ja, dieser Weg ist klar. Aber was tun, wenn OpenHAB eine Aktion triggern soll. Z.B. mittels Taster den E-Öffner des Gartentors schalten. Dass muss ich mir noch ansehen. Ich komme leider auch nicht allzu oft dazu.

**Comment by hubsif** [comment]
Ich kenne OpenHAB (noch) nicht wirklich, aber könnte man dazu nicht das filesystem keyboard per SSH verwenden? Also sowas wie:

    ssh <doorpi IP> -c "echo 1 > /var/DoorPI/keyboards/input/gartentor"

**Comment by Schwa-l-be** [comment]
ungefähr so wäre es möglich.
OpenHAB unterstützt die Funktion einen SSH Befehl zu senden nicht direkt, dazu müsstest du über das exec Binding gehen.
Bin im moment leider komplett raus aus DoorPi und kann nichts zum Webservice #57 sagen, sonst wäre natürlich die einfachste Möglichkeit diesen aufzurufen.

**Comment by motom001** [comment]
in der #57 ist das Thema gelöst und sollte auch hier die Lösung sein.
DoorPi kann andere Systeme antriggern und selsbt per Webservice oder SSH angetriggert werden.
