### ISSUE TITLE
Skripts ausführen bei Event

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#68]
aus dem [Forum forum-raspberrypi.de](http://www.forum-raspberrypi.de/Thread-haussteuerung-doorpi-voip-wechselsprechanlage-tuersprechanlage?pid=146376#pid146376):

>Hi Thomas,
>
>lässt es sich einbauen, dass ich bei den EVENTs ein Skript angeben kann, welches dann ausgeführt wird?

**Comment by pirurim** [comment]
Hi Thomas,
bist du an der Umsetzung dran oder kann man dir behilflich sein? Ich habe bei meinem Projekt folgende Dinge umgesetzt:
Beim Klingeln wird eine Message über telegram (via pexpect) und ein shell Befehlt/Script (via subprocess) ausgeführt.

Wie gesagt, falls du Hilfe brauchst einfach melden (http://www.forum-raspberrypi.de/User-sdk)

**Comment by motom001** [comment]
Wenn in der Config eine Aktion gefunden wird (in dem Fall sleep) wird unter [DoorPi/doorpi/action/SingleActions/](https://github.com/motom001/DoorPi/tree/master/doorpi/action/SingleActions) nach einer Datei gesucht, die den gleichen Namen trägt (-> z.B. [sleep.py](https://github.com/motom001/DoorPi/blob/master/doorpi/action/SingleActions/sleep.py)) und innerhalb dieser Datei die Funktion [get](https://github.com/motom001/DoorPi/blob/master/doorpi/action/SingleActions/sleep.py#L11) aufgerufen. Die Funktion get muss ein Object der Klasse [SingleAction](https://github.com/motom001/DoorPi/blob/master/doorpi/action/base.py) zurückliefern. 

Konstruktor dieser Klasse erwartet als ersten Parameter eine Callback Funktion und als optionale weitere Parameter \*args und \**kwargs.

Die Aktion [mailto](https://github.com/motom001/DoorPi/blob/master/doorpi/action/SingleActions/mailto.py) könnte als Vorlage für "Message über telegram" dienen (Vorschlag für Dateiname "telegram.py").
Die Aktion [sleep](https://github.com/motom001/DoorPi/blob/master/doorpi/action/SingleActions/sleep.py) könnte als Vorlage für "shell Befehlt/Script" dienen (Vorschlag für Dateiname "os_execute.py").
