### ISSUE TITLE
Starten nach update nicht möglich

### ISSUE THREAD

**Issue by redfox1977** [motom001/DoorPi#69]
Nach dem update auf die neuste Version von doorpi und einem rpi-update kann ich den doorpi nicht mehr starten. 
Fehlermeldung:
2015-05-12 12:35:31,115 [TRACE]         [conf.config_object] get_string for key sipphonetyp in section SIP-Phone (default: autodetect) returns linphone
2015-05-12 12:35:31,261 [ERROR]         [sipphone.SipphoneInterface] sipphone linphone not found @ sipphone.from_linphone
Traceback (most recent call last):
  File "/opt/download/DoorPi/doorpi/sipphone/SipphoneInterface.py", line 19, in load_sipphone
    sipphone = importlib.import_module('sipphone.from_'+sipphone_name).get(
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/download/DoorPi/doorpi/sipphone/from_linphone.py", line 11, in <module>
    import linphone as lin
ImportError: No module named linphone
2015-05-12 12:35:31,268 [ERROR]         [__main__] Exception NameError: sipphone linphone not found (No module named linphone)
Traceback (most recent call last):
  File "./main.py", line 159, in main_as_application
    try:                        doorpi.DoorPi(parsed_arguments).run()
  File "/opt/download/DoorPi/doorpi/doorpi.py", line 203, in run
    if not self.__prepared: self.prepare(self.__parsed_arguments)
  File "/opt/download/DoorPi/doorpi/doorpi.py", line 109, in prepare
    self.__sipphone = load_sipphone()
  File "/opt/download/DoorPi/doorpi/sipphone/SipphoneInterface.py", line 26, in load_sipphone
    raise SipphoneNotExists('sipphone %s not found (%s)'%(sipphone_name, str(exp)))
SipphoneNotExists: sipphone linphone not found (No module named linphone)

ein umstellen auf pjsua bringt nur einen Speicherfehler zu Tage...

Bitte um Hilfe...

**Comment by motom001** [comment]
Diese Datei
https://github.com/motom001/DoorPi/blob/master/doorpi/sipphone/from_linphone.py
fehlt oder ist nicht lesbar oder ähnliches.
Die Datei löschen und neu erzeugen - eventuell mit copy und paste.

Das andere Thema ist das Speicherproblem bei pjsua - dafür würden mich Log-Dateien interessieren.
Danke!

**Comment by redfox1977** [comment]
Hallo und Danke für die Antwort.

Habe alles so gemacht geht immer noch nicht!

Welche Abhängigkeiten müssen noch erfüllt werden? Habe alles zu linphone installiert.

Welche Logs hättest du gerne? Kann leider auch nichts in den logs zum Speicherfehler lesen…

 

 

Von: Thomas [mailto:notifications@github.com] 
Gesendet: Dienstag, 12. Mai 2015 22:10
An: motom001/DoorPi
Cc: Sven Pietack
Betreff: Re: [DoorPi] Starten nach update nicht möglich (#69)

 

Diese Datei
https://github.com/motom001/DoorPi/blob/master/doorpi/sipphone/from_linphone.py
fehlt oder ist nicht lesbar oder ähnliches.
Die Datei löschen und neu erzeugen - eventuell mit copy und paste.

Das andere Thema ist das Speicherproblem bei pjsua - dafür würden mich Log-Dateien interessieren.
Danke!

**Comment by motom001** [comment]
Okay - ganz auf Anfang. Zuerst kümmern wir uns um das linphone-Problem, danach pjsua, okay?
Diese Zeile hier:
`2015-05-12 12:35:31,261 [ERROR] [sipphone.SipphoneInterface] sipphone linphone not found @ sipphone.from_linphone`
zeigt an, dass die Datei nicht gefunden wurde oder nicht gelesen werden kann.
Deshalb bitt prüfen, ob es diese Datei gibt. Normalerweise ist diese unter:
/home/DoorPi/doorpi/sipphone/from_linphone.py
zu finden. Wenn es diese Datei gibt, dann bitte prüfen ob die auch lesbar ist (z.B. mit cat /home/DoorPi/doorpi/sipphone/from_linphone.py).
Wenn beides funktioniert, dann bitte noch einmal melden. Ich gehe aber davon aus, dass schon eins der beiden Dinge nicht klappt.

**Comment by redfox1977** [comment]
Guten Morgen, Das ist immer das 1. Was ich kontrolliere.habe alle verechtigungen neu gesetzt auf pi:pi. Die datei wird auch kompiliert also alles lesbar.. das hatte mich ja auch gewundert.ich habe auch schon versucht doorpi neu runtergeladen und dann mit der standart config zu starten. Selbes bild. Hatte auch schon versucht mit autodetect zu starten, leider selbes Bild.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Thomas <notifications@github.com> 
Datum: 12.05.2015  22:53  (GMT+01:00) 
An: motom001/DoorPi <DoorPi@noreply.github.com> 
Cc: Sven Pietack <redfox7719@googlemail.com> 
Betreff: Re: [DoorPi] Starten nach update nicht möglich (#69) 

Okay - ganz auf Anfang. Zuerst kümmern wir uns um das linphone-Problem, danach pjsua, okay?

Diese Zeile hier:

2015-05-12 12:35:31,261 [ERROR] [sipphone.SipphoneInterface] sipphone linphone not found @ sipphone.from_linphone

zeigt an, dass die Datei nicht gefunden wurde oder nicht gelesen werden kann.

Deshalb bitt prüfen, ob es diese Datei gibt. Normalerweise ist diese unter:

/home/DoorPi/doorpi/sipphone/from_linphone.py

zu finden. Wenn es diese Datei gibt, dann bitte prüfen ob die auch lesbar ist (z.B. mit cat /home/DoorPi/doorpi/sipphone/from_linphone.py).

Wenn beides funktioniert, dann bitte noch einmal melden. Ich gehe aber davon aus, dass schon eins der beiden Dinge nicht klappt.

**Comment by motom001** [comment]
Entschuldigung, mein Fehler. Ich hatte die Fehlermeldung genauer lesen sollen. 
http://linphone.org/wiki/doku.php/raspberrypi:start

Danach sollte es funktionieren...

**Comment by redfox1977** [comment]
Danke das hatte ich gesucht.kann man das in den Installer mit rein nehmen? Hatte schon geahnt das was fehlt...



Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Thomas <notifications@github.com> 
Datum: 13.05.2015  10:57  (GMT+01:00) 
An: motom001/DoorPi <DoorPi@noreply.github.com> 
Cc: Sven Pietack <redfox7719@googlemail.com> 
Betreff: Re: [DoorPi] Starten nach update nicht möglich (#69) 

Entschuldigung, mein Fehler. Ich hatte die Fehlermeldung genauer lesen sollen. 

http://linphone.org/wiki/doku.php/raspberrypi:start

Danach sollte es funktionieren...

**Comment by motom001** [comment]
Jop, soll in den installer mit rein...
Nur leider ist meine Zeit begrenzt. Wenn das jemand übernehmen möchte, dann gerne...

**Comment by motom001** [comment]
Kann der Issue damit geschlossen werden?
Das mit dem Installer ist ein anderes Thema...
