### ISSUE TITLE
DoorPI kann nicht mit pjsua starten

### ISSUE THREAD

**Issue by redfox1977** [motom001/DoorPi#74]
Hallo,
habe nun ein Rasbian (wheezle) neu aufgesetzt und alles neu installiert.
Wenn ich auf pjsua wechsle kommt immer diese Fehlermeldung.

Leider kann ich kein python, so ist meine hilfe bei der Fehlersuch eingeschränkt...

2015-05-23 18:44:09,030 [TRACE]         [action.handler] register Event OnSipPhoneCallTimeoutMaxCalltime from sipphone.from_pjsua
2015-05-23 18:44:09,032 [TRACE]         [action.handler] added event_name OnSipPhoneCallTimeoutMaxCalltime an register source sipphone.from_pjsua
2015-05-23 18:44:09,040 [ERROR]         [__main__] Exception NameError: can't set attribute
Traceback (most recent call last):
  File "./main.py", line 159, in main_as_application
    try:                        doorpi.DoorPi(parsed_arguments).run()
  File "/home/DoorPI/doorpi/doorpi.py", line 214, in run
    if not self.__prepared: self.prepare(self.__parsed_arguments)
  File "/home/DoorPI/doorpi/doorpi.py", line 130, in prepare
    self.__sipphone     = load_sipphone()
  File "/home/DoorPI/doorpi/sipphone/SipphoneInterface.py", line 22, in load_sipphone
    conf_post = conf_post
  File "/home/DoorPI/doorpi/sipphone/from_pjsua.py", line 23, in get
    def get(*args, **kwargs): return Pjsua()
  File "/home/DoorPI/doorpi/sipphone/from_pjsua.py", line 97, in __init__
    self.current_call = None
AttributeError: can't set attribute

MFG Sven

**Comment by motom001** [comment]
sollte gelöst sein - bitte mal testen
Meine aktuelle Teststellung umfasst kein pjsua mehr :P

**Comment by hubsif** [comment]
Es gibt scheinbar noch mehr Probleme mit pjsua, die ich mal angefangen habe zu fixen, aber momentan vom einen ins nächste komme.

@redfox1977 
Gibt es einen bestimmten Grund, warum du lieber pjsua als linphone verwenden willst?
Wenn ja würde ich mal sehen, ob ich dir helfen kann, dann kann motom001 sich auf die Weiterentwicklung konzentrieren. Wenn nein, würde ich dir empfehlen fürs erste auf linphone zu wechseln, da hierauf momentan der Fokus liegt und damit auch getestet wird.

**Comment by motom001** [comment]
1. THX @hubsif 
2. new version of pjsua: http://www.pjsip.org/

**Comment by redfox1977** [comment]
Nein ich hatte nur das Problem das Linphone beim Klingeln immer im sek. Takt neu angewählt. Bin auch für den wechsel auf Linphone.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: hubsif <notifications@github.com> 
Datum: 24.05.2015  13:56  (GMT+01:00) 
An: motom001/DoorPi <DoorPi@noreply.github.com> 
Cc: Sven Pietack <redfox7719@googlemail.com> 
Betreff: Re: [DoorPi] DoorPI kann nicht mit pjsua starten (#74) 

Es gibt scheinbar noch mehr Probleme mit pjsua, die ich mal angefangen habe zu fixen, aber momentan vom einen ins nächste komme.

@redfox1977 

Gibt es einen bestimmten Grund, warum du lieber pjsua als linphone verwenden willst?

Wenn ja würde ich mal sehen, ob ich dir helfen kann, dann kann motom001 sich auf die Weiterentwicklung konzentrieren. Wenn nein, würde ich dir empfehlen fürs erste auf linphone zu wechseln, da hierauf momentan der Fokus liegt und damit auch getestet wird.
