### ISSUE TITLE
DoorPiWeb kann seite nicht laden

### ISSUE THREAD

**Issue by redfox1977** [motom001/DoorPi#78]
Ich wollte man DoorPiWeb ausprobieren, aber wenn ich es starte dann kommen nur Fehlermeldungen...
was mache ich falsch?
Habe DoorPiWeb heruntergeladen und in der Config eingetragen.

Dann kommt nur das er das index.html nicht finden kann.

**Comment by motom001** [comment]
Sollte behoben sein. 
Übrigens, wenn der pi eine Internet Verbindung hat, dann muss doorpiweb nicht runter geladen werden. Es lädt immer nur die Seiten, die wirklich benötigt werden. Ich schließe das Ticket, wenn das Problem noch besteht, dann bitte wieder eröffnen. Danke...
