### ISSUE TITLE
DoorPi am BananaPi keine Ordner

### ISSUE THREAD

**Issue by Tobi-BPi** [motom001/DoorPi#81]
Hi!

ich habe versucht mit hilfe des Wiki den DoorPi auf meine 
Banane zu installieren!
In der Wiki (Installation BananaPi) sind unten ein paar Fehler:
Zeile 2 "get" vergessen
Zeile 5 "&&" vergessen

Was aber nicht mein eigentliches Problem darstellt. 

Ich kann DoorPi öffnen installieren updaten PiFace installieren usw...... 
Aber ich habe keinen ORDNER in der die Konfigurationsdatei steckt! 

Wenn ich mit locate nach DoorPi suche finde ich nur das DoorPI.sh
und einen leeren Ordner unter /var/DoorPI

Kann mir jemand helfen bzw was mache ich falsch?

grüße
Tobi

**Comment by hubsif** [comment]
Hallo Tobi,

Ich habe zwar keinen BananaPi, aber vielleicht kann ich dir trotzdem helfen.
Im Wiki wird auf das Installationsskript verwiesen, dass zwar grundsätzlich funktionieren sollte, aber für das derzeit nicht ganz funktionale pjsua ausgelegt ist. Du solltest die Installation momentan besser per Hand durchführen. Schau dir mal meine ersten Entwürfe für neue Anleitungen an, [Installation](https://github.com/hubsif/DoorPi/wiki/Installation), [Konfiguration](https://github.com/hubsif/DoorPi/wiki/Konfiguration), vielleicht helfen die.

Trotz allem solltest du - wenn das Installationsskript funktioniert hat - ein Verzeichnis /home/DoorPI haben. Dort sollte es die Datei "conf/doorpi.cfg" geben, die standardmäßig geladen wird.
Falls nicht, hat wohl der Installer nicht richtig funktioniert. Dann versuche es doch bitte manuell.

**Comment by Tobi-BPi** [comment]
Hi@all

kleines Feedback zur Banane und deiner Anleitung!
Als es um den Benutzer ging, in deinem Beispiel "pi" muss der Bananen Nutzer natürlich 
bananapi eingeben. 
Aber die richtig großen Probleme kamen nun erst mit der System-Dienst installation! 

bananapi@lemaker ~ $ sudo cp docs/service/doorpi /etc/init.d/
cp: cannot stat `docs/service/doorpi': No such file or directory

bananapi@lemaker ~ $ sudo update-rc.d doorpi defaults
update-rc.d: using dependency based boot sequencing
update-rc.d: error: unable to read /etc/init.d/doorpi

vielleicht konnte ich euch helfen bzw. könnt ihr mir nun helfen. :-)
grüße 
schönen Sonntag
Tobi

**Comment by vanso-hubsi** [comment]
Meine Anleitung zur Systemdienstinstallation setzt fälschlicherweise voraus, dass man ins Verzeichnis "/home/DoorPI" gewechselt hat. Das hier sollte besser funktionieren:

    sudo cp /home/DoorPI/docs/service/doorpi /etc/init.d/
    sudo update-rc.d doorpi defaults

Hast du mittlerweile die doorpi.cfg finden können?

**Comment by hubsif** [comment]
Meine Anleitung zur Systemdienstinstallation setzt fälschlicherweise voraus, dass man ins Verzeichnis "/home/DoorPI" gewechselt hat. Das hier sollte besser funktionieren:

    sudo cp /home/DoorPI/docs/service/doorpi /etc/init.d/
    sudo update-rc.d doorpi defaults

Hast du mittlerweile die doorpi.cfg finden können?

**Comment by Tobi-BPi** [comment]
HI, 
sorry für die späte Antwort!
DANKE für deine Mühe! 
Mit deiner anleitung funktioniert es. 

PiFace (plus Bananapi) ist derzeit am laufen mit LED2 ON und LED7 BLINK
(hab in der config schon herumgespielt und auf LED6 BLINK geändert um 
zu sehen, ob sich was tut wenn ich etwas ändere. 

appropo sehen ob sich was tut... 
muss ich eine neue ISSUE dazu öffnen? 

Ich wollte soeben checken was und wie mein PiFace alles aufnimmt und abgibt. 
Deshalb wollte ich den DoorPi in `--trace` ausführen. 

Jedoch kommt ein haufen an Text der aussieht wie eine Logfile und endet abrupt mit
`DoorPi successfully shutdown` das ist aber so nicht in Ordnung, oder?

mfg
Tobi

**Comment by norbi-bpi** [comment]
Hi,
ich möchte auf meinen Banana Pi unter lubuntu DoorPi installieren.  sudo ./DoorPI.sh funktioniert. [A]bhaengigkeiten installieren tritt folgender Fehler auf.

/usr/bin/ld: /usr/src/pjproject-2.3/pjsip/lib/libpjsua-armv7l-unknown-linux-gnueabihf.a(pjsua_acc.o): relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard' can not be used when making a shared object; recompile with -fPIC
/usr/src/pjproject-2.3/pjsip/lib/libpjsua-armv7l-unknown-linux-gnueabihf.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
make: *** [all] Error 1
Es ist ein Fehler aufgetreten..
Abbruch
Vielleicht kann mir jemand weiter helfen - Danke.

**Comment by Tobi-BPi** [comment]
Hallo, 

ich habe auf meiner Banane ein Bananian (Raspbian Clon) drauf. 
Ob und wie es mit der kompatibilität zu deinen Lubuntu ausssieht werden dir die 
Profis hier genauer erläutern können! 
JEDOCH rate ich dir mal das ganze nicht per Intallations-script sondern manuell zu 
installieren. 
Folge bitte den links oben im 2. Beitrag von hubsif und versuche es manuell. 
bei mir hat es dann geklappt. 

Tobi

**Comment by norbi-bpi** [comment]
Hi,
ich möchte auf meinen Banana Pi unter lubuntu DoorPi installieren.  sudo ./DoorPI.sh funktioniert. [A]bhaengigkeiten installieren tritt folgender Fehler auf.

/usr/bin/ld: /usr/src/pjproject-2.3/pjsip/lib/libpjsua-armv7l-unknown-linux-gnueabihf.a(pjsua_acc.o): relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard' can not be used when making a shared object; recompile with -fPIC
/usr/src/pjproject-2.3/pjsip/lib/libpjsua-armv7l-unknown-linux-gnueabihf.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
make: *** [all] Error 1
Es ist ein Fehler aufgetreten..
Abbruch
Vielleicht kann mir jemand weiter helfen - Danke.

**Comment by norbi-bpi** [comment]
Hi,
Danke für die Info. Werd ich machen.

**Comment by motom001** [comment]
ist das Thema noch aktuell?

**Comment by norbi-bpi** [comment]
Nein
