### ISSUE TITLE
Linphone Support "Läuft, aber mit Startschwierigkeiten"

### ISSUE THREAD

**Issue by frrr1** [motom001/DoorPi#83]
-Liebe DoorPi-Freunde,

da ich für andere User an dieser Stelle festhalten möchte wie ich den Video Support mit Linphone geschafft habe (Pi2, PiFace, RaspiCam, Client: Android/Linphone) und mir dieser Weg (Issue) am einfachsten erschien, bitte ich euch folgendes ins Wiki aufzunehmen. (Ich bin dazu auch gerne selbst bereit, evtl. kann mir jemand sagen, wie ich das Wiki modifizieren kann.)

1.  Linphone installieren https://wiki.linphone.org/wiki/index.php/Raspberrypi:start
2. sudo modprobe bcm2835-v4l2, damit die RaspiCam als /dev/video0 registriert wird
(mit UV4L habe ich es nicht geschafft, dass ich ein Bild bekomme)
3. doorpi.cfg:
In der Sektion [SIP-Phone] die folgenden Parameter/Werte setzen:
sipphonetyp = linphone
video_device =  V4L2: /dev/video0
video_size = vga

4. Testen

Sollte es jetzt noch immer nicht funktionieren noch ein wichtiger Hinweis: Asterisk 11 unterstützt kein VP8 (Video Codec) Passthrough. Solltet Ihr also eine Asterisk Anlage verwenden müsst Ihr min. Auf Version 12 gehen. Man kann allerdings testen ob alles funktioniert indem man im doorpi.cfg einen Eintrag <input-pin-nr> = call:<user>@<linphoneclientip> macht.

lG

**Comment by hubsif** [comment]
Hallo frrr1,

Wie du scheinbar gesehen hast, hab ich meine Wiki-Arbeit jetzt hochgeladen. Sie sollte das von dir genannte hoffentlich beinhalten.
Trotzdem sehr vielen Dank für deine Hinweise!
