### ISSUE TITLE
sudo service doorpi status wirft Fehler

### ISSUE THREAD

**Issue by hubsif** [motom001/DoorPi#84]
Der "status" Befehl des Serviceskriptes sollte meiner Ansicht nach überarbeitet werden. Es sollte unabhängig vom Webserver funktionieren. Meiner Ansicht nach reicht es auch, wenn es wie bei den meisten Diensten in der Linux-Welt unabhängig von Programmlogik ist, sondern einfach nur das PID File überprüft und ausgibt ob der Dienst läuft oder nicht.

**Comment by motom001** [comment]
Und was ist wenn DoorPi als Anwendung gestartet ist? Dann gibt es kein pid-File...
Was soll dann ausgegeben werden?

**Comment by motom001** [comment]
Wäre es nicht besser, wenn ein Prozess mit dem Namen "DoorPi" gesucht werden würde?
Wie könnte das realisiert werden? Hat jemand passende Vorschläge?
Passende Stelle wäre diese hier:
https://github.com/motom001/DoorPi/blob/master/doorpi/main.py#L97

**Comment by motom001** [comment]
Oder soll das Abfragen nach dem Prozess vielleicht lieber hier drin sein:
https://github.com/motom001/DoorPi/blob/master/docs/service/doorpi#L34

**Comment by vanso-hubsi** [comment]
Würde beides mit ja beantworten. Es gibt denke ich viele init Skripte, die nicht nur das PID-File, sondern auch die Prozessliste überprüfen, sowohl bei "status" als auch den anderen Befehlen. Ich werd mal recherchieren und was entsprechendes hier vorschlagen.

**Comment by hubsif** [comment]
Würde beides mit ja beantworten. Es gibt denke ich viele init Skripte, die nicht nur das PID-File, sondern auch die Prozessliste überprüfen, sowohl bei "status" als auch den anderen Befehlen. Ich werd mal recherchieren und was entsprechendes hier vorschlagen.

**Comment by hubsif** [comment]
also ich hab mir das mit dem Init Skript mal angesehen. Wie es scheint ist es "standardkonform" die LSB-Skripte einzubinden (zumindest ist das bei 90% der Skripte so). Dazu setzt man im Init Skript oben:

    . /lib/lsb/init-functions

Ab da passiert alles magisch von selbst. Eine "status" Funktion muss man nicht mehr implementieren, das kommt dann von systemd und prüft wohl auch, ob der Prozess noch läuft.

Was allerdings nicht geprüft wird, ist, ob DoorPi als Anwendung (manuell gestartet) läuft. Das ist wohl grundsätzlich nicht vorgesehen und funktioniert bei keinem Init Skript in raspbian wirklich. Die Debianer scheinen die Systemdienste als eigenes Ding zu sehen und davon auszugehen, dass wenn man Systemdienst-Applikationen von Hand startet, schon weiß, was man tut :).

Meinst du, das würde reichen? Oder soll das Init Skript wirklich prüfen, ob irgendeine Instanz von DoorPi läuft (alles möglich)?
(andersrum prüft DoorPi beim manuellen Start ja auch nicht, ob schon ein DoorPi als Service läuft...)

**Comment by motom001** [comment]
Das sollte reichen, denn als Anwendung ist es ja nur der erste Start, wenn überhaupt.
Könntest du dich da bitte dein kümmern? Ich kämpfe noch mit doorpiweb...
