### ISSUE TITLE
doorpi.conf fehlt

### ISSUE THREAD

**Issue by KingderNoob** [motom001/DoorPi#91]
Hi,

Die doorpi.cfg ist nicht mehr vorhanden. Bräuchte diese Datei. Sonst super Projekt.

**Comment by Schwa-l-be** [comment]
Die Beispiel config wurde gelöscht, da es mehr Probleme brachte als Vorteile.
Du kannst deine Datei aber nach dem Schema wie im Wiki beschrieben aufbauen:
https://github.com/motom001/DoorPi/wiki/doorpi.cfg
