### ISSUE TITLE
Fehlermeldungen beim stoppen des Services doorpi

### ISSUE THREAD

**Issue by pistreamer** [motom001/DoorPi#94]
Folgende Fehlermeldung erhalte ich wenn ich den Service stoppe:

$ sudo service doorpi stop
[....] Stopping VoIP Intercom Service: DoorPi
    ___                  ___ _
   /   \___   ___  _ __ / _ (_)  VoIP Door-Intercomstation with Raspberry Pi
  / /\ / _ \ / _ \| '__/ /_)/ |  version:   2.3 #231
 / /_// (_) | (_) | | / ___/| |  license:   CC BY-NC 4.0, 2014-2015
/___,' \___/ \___/|_| \/    |_|  URL:       <https://github.com/motom001/DoorPi>

Authors:    Thomas Meissner <motom001@gmail.com>
Supporter:  Phillip Munz <office@businessaccess.info>
            Hermann DÃ¶tsch <doorpi1@gmail.com>
            Dennis HÃ¤uÃler <haeusslerd@outlook.com>
            Hubert Nusser <hubsif@gmx.de>
            Michael Hauer <frrr@gmx.at>
            missing someone? -> sorry -> mail me

2015-08-20 09:41:43,741 [INFO]          [__main__] loaded with arguments: ['/home/DoorPI/doorpi/main.py', 'stop']
Traceback (most recent call last):
  File "/home/DoorPI/doorpi/main.py", line 181, in <module>
    entry_point()
  File "/home/DoorPI/doorpi/main.py", line 175, in entry_point
    raise SystemExit(main_as_daemon(sys.argv))
  File "/home/DoorPI/doorpi/main.py", line 149, in main_as_daemon
    doorpi.DoorPi().destroy()
  File "/home/DoorPI/doorpi/doorpi.py", line 185, in destroy
    logger.debug("Threads before starting shutdown: %s", self.event_handler.threads)
AttributeError: 'NoneType' object has no attribute 'threads'
 failed!

**Comment by motom001** [comment]
Lief DoorPi wirklich oder wolltest Du ein nicht gestartetes DoorPi stoppen?

**Comment by pistreamer** [comment]
hi doorpi lief vorhin... hatte den service manuell gestartet und danach eben gestoppt...

**Comment by motom001** [comment]
Manuell gestartet mit?
    sudo service doorpi start

@hubsif: kannst du das übernehmen?

**Comment by pistreamer** [comment]
sudo service doorpi start... ja thx...

**Comment by motom001** [comment]
und noch eine Frage dazu - welches Betriebssystem benutzt Du? Speziell die Frage - benutzt Du wheezy?

**Comment by pistreamer** [comment]
Hallo ja von https://www.raspberrypi.org/downloads/raspbian/

**Comment by hubsif** [comment]
ja, kann ich übernehmen. Leider aber erst in ca. 10 Tagen...

**Comment by motom001** [comment]
Kann ich den Issue schließen?

**Comment by maxkr2** [comment]
Hi Thomas,

hatte den Fehler am WE noch. Habe aber noch eine ältere DoorPi-Version laufen. Kann aber erst heute Abend testen...

**Comment by maxkr2** [comment]
Hallo Thomas,

habe gerade doch die neue Version versucht (dachte mein DoorPi wäre aus...). Bekomme nun was anderes:
Traceback (most recent call last):
  File "/usr/local/bin/doorpi_cli", line 9, in <module>
    load_entry_point('DoorPi==2.4.1.0', 'console_scripts', 'doorpi_cli')()
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.0-py2.7.egg/doorpi/main.py", line 174, in entry_point
    raise SystemExit(main_as_daemon(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.0-py2.7.egg/doorpi/main.py", line 130, in main_as_daemon
    from daemon import runner
ImportError: cannot import name runner

Viele Grüße,
Max

**Comment by motom001** [comment]
Aber ein Start von DoorPi als Daemon funktioniert?

**Comment by maxkr2** [comment]
Ja, läuft einwandfrei. War auch mit der 2.4.0.7 schon so. Die o.g. FM mit dem Thread-Fehler aber funktioniert hat es trotzdem...

**Comment by maxkr2** [comment]
Hi Thomas,
muss hier leider noch eine Baustelle aufmachen bzw. die bestehende Erweitern: Der Fehler mit "cannot import name runner" kommt jetzt bei mir nachdem ich den RasPi gerade neu gestartet habe. DoorPi startet nicht mehr... ;-( Habe aber gerade deinen Post im Forum gesehen. Liegt es irgendwie an den Pfaden und oder Rechten?!

**Comment by motom001** [comment]
Mist - ich hab das falsche daemon paket hinzugefügt.
Früher kam es über apt-get install python-daemon
Jetzt kommt es von pypi als paket daemon
Das ist aber nicht das gleiche Paket...
ARGHHHH

-> Verweis auf #113 <-

**Comment by maxkr2** [comment]
Issue 94 kann an sich geschlossen werden. 

Nur der Restart ist zu schnell. Ich habe mal ein sleep 5 in der /etc/init.d/doorpi eingebaut und damit geht der Restart dann auch:
 do_stop_cmd
 sleep 5
 do_start_cmd

vielleicht baust du das im nächsten Release ein oder hast eine noch bessere Idee?!
