### ISSUE TITLE
DoorPi Syntax

### ISSUE THREAD

**Issue by Schwa-l-be** [motom001/DoorPi#95]
nachdem ich jetzt wieder mehr Zeit habe, bin ich gerade dabei die Wiki Seiten ins englische zu übersetzen und wenn ich wieder voll im Thema bin auch zu überarbeiten.
Mir ist jetzt aufgefallen, dass die Instllation unter DoorPI stattfindet, sollte das nicht mal geändert werden bzw. wie ist denn jetzt der aktuelle Syntax damit nicht wegen einem "i" Probleme auftreten.

**Comment by pistreamer** [comment]
Hi Schwa-l-be.. ich habe doorpi.cfg in meinem Fork um Webserver Einstellungen und Berechtigungen erweitert und könnte gemerged werden. Jedoch habe ich keine Rechte für den direkten Zugriff...pls help

**Comment by Schwa-l-be** [comment]
@pistreamer kannst du das Wiki nicht direkt hier bearbeiten (Edit Button oben rechts auf der Seite)? Das sollte auch ohne jegliche Berechtigungen funktionieren.
Habs dennoch mal hinzugefügt.

**Comment by motom001** [comment]
Die Schreibweise von DoorPi sollte entweder DOORPI, doorpi oder DoorPi sein.
Die Schreibweise DoorPI hoffe ich irgendwann mal wieder raus zu bekommen.
Am Liebsten wäre mir "DoorPi" - z.B. wie in der metadata.py:
```
    ___                  ___ _
   /   \___   ___  _ __ / _ (_) 
  / /\ / _ \ / _ \| '__/ /_)/ |  
 / /_// (_) | (_) | | / ___/| |  
/___,' \___/ \___/|_| \/    |_|  
```

**Comment by Schwa-l-be** [comment]
dann mach ich mich nachher daran die anderen Schreibweisen aus dem Wiki zu verbannen und in "DoorP2i für die Installation, etc. einzufügen

**Comment by pistreamer** [comment]
Hallo.. nein ich habe leider keinen Edit Button, nur auf meiner geforkten Seite. Alles klar "corporate design" beim Namen (DoorPi) sollte überall gleich sein, werde in Zukunft drauf achten!

**Comment by motom001** [comment]
Ich glaube DoorP2i war nur ein Schreibfehler - es gibt aktuell nur DoorPi

**Comment by Schwa-l-be** [comment]
Oh sorry das war echt ein Schreibfehler :D der sollte sich im Wiki nicht blicken lassen

**Comment by pistreamer** [comment]
kk... np ich gebe einfach wieder Bescheid, wenn ich was geändert habe ;)

**Comment by motom001** [comment]
@Schwa-l-be: Ich versuche gerade diese reinen Konfigurationsparameter auch im Quellcode abzubilden, da ich z.B. in der Weboberfläche auch die Default-Werte anzeigen lassen möchte.
Ein erster, aber nicht vollständig richtiger Schritt ist diese Stelle:
https://github.com/motom001/DoorPi/tree/master/doorpi/status/requirements_lib
Das sit fürs Sipphone z.B. beschrieben, welche Events es haben kann:
`dict( name = 'OnSipPhoneCreate', description = 'Das SIP-Phone wurde erstellt und kann gestartet werden.')`
Oder auch welche Parameter es geben könnte:
dict( section = SIPPHONE_SECTION, key = 'video_device', type = 'string', default = '', mandatory = False, description = 'Kamera, die für die Aufnahme genutzt wird - wenn nichts angegeben wird, dann wird die erst Beste genutzt. Bitte dazu in der LOG-Datei nach "possible videodevices:" suchen')

Zu Ende gedacht ist das bei weitem noch nicht, aber die Zielstellung ist für mich klar. Das reine Dokumentieren von Parametern sollte nicht Eure kostbare Zeit rauben, sondern im Quellcode verankert sein. Daraus soll die Doku dann automatisch erstellt werden können. Der Teil Doku, wie es installiert, gestartet und eingerichtet werden kann, welche Tipps und Tricks es gibt und was Beschreibung im Allgemeinen angeht, werde ich nie automatisieren können. Verstehst Du, was ich meine? Ist das in Deinem Sinne oder mach ich damit bei Dir mehr kaputt?

**Comment by Schwa-l-be** [comment]
Das wäre definitiv in meinem Sinne. Die Konfiguration bietet so viele Möglichkeiten, die Seiten füllen würde um alles genau zu definieren. Wenn wir es so machen wie du sagst, fällt das weg und die gesparte Zeit könnte man dann auch zur Problemlösung nutzen.
