### ISSUE TITLE
Feature Request: Anläut History

### ISSUE THREAD

**Issue by pistreamer** [motom001/DoorPi#96]
Hi, zusätzlich zur Video/Audio Aufnahme wäre eine Funktion nicht schlecht, die ein Bild von der Person die anläutet (vor Call) durchführt. Das bedeutet sobald jemand anläutet wird automatisch bzw. über Konfiguration eingestellt ein Bild gemacht und gespeichert (doorpi/media/pictures). Die Anzahl wie viele Bilder gespeichert in der History werden sollte auch eingestellt werden können und dann sollten die Bilder am Webserver angezeigt werden können. 

Bei diesem Feature geht es um zusätzliche Sicherheit, da Einbrecher oft über Klingeln rausfinden wollen wann wer zu Hause ist. Zusätzlich können Spassklingler ausgeforscht werden und zur Rede gestellt werden ;). Somit kann eine Verfolgung auch ohne Aufnahme von jedem Call stattfinden, was Ressourcen spart. Ich weiss, man kann durch die out Aktion beim richtigen Event ein Skript auslösen was das übernimmt, aber die zusätzliche Anzeige dann am Webserver wäre nice...

Was meint ihr davon?

**Comment by motom001** [comment]
Ähnliche Ideen hatte ich auch schon, allerdings dann zurückgestellt, denn wer das unbedingt möchte, will Bilder haben BEVOR geklingelt wird. So könnte man bei Bewegungserkennung bereits die Aufnahme starten. Das liegt aber (aktuell) noch vor DoorPi Events und Actions :)

Meine Idee weiter war dann, das klingt jetzt komisch, ein keyboard mit dem Namen "from_ip_camera" oder "from_picam" einzubinden, dass mit DoorPi Events darauf reagiert, wenn Bewegung erkannt werden.

Sollte an sich kein Problem sein - zumal dann ein keyboard wäre, dass irgendwann auch eine Gesichtserkennung durchführen könnte...

Aber die Ressourcen vom Pi und mir sind begrenzt...

Zurück zu Deiner Idee:
Aktuell würde ich das mit einer neuen Action lösen, die ein Bild aufnimmt. Eventuell eine zweite Action die ein zeitlich begrenztes Bild aufnimmt.
Die Idee mit dem Bild im DoorPiWeb nehme ich mal mit, aber wird zurückgestellt. Vorher müssen die Grundfunktionalitäten stehen, bevor ich dort neue Funktionen aufnehme.

Okay so?

**Comment by pistreamer** [comment]
Hallo ja ist ok so! Motion detection mit Gesichtserkennung wären schon eine feine Sache, jedoch wie du schon angesprochen hast ist das ein Overkill für die Raspberry Hardware und sicherheitstechnisch hätte ich da auch meine Bedenken. Motion detection alleine wäre hingegen denke ich mir möglich, dazu gibt es genügend Projekte. Jedenfalls habe ich noch irgendwo ein Script rumliegen, dass ein Bild von Raspberry Kamera aufnimmt, also sollte das zurzeit mit Events und out Action umgesetzt werden können. Jedoch denke ich, dass das EVENT_OnSipPhoneMakeCall ungeeignet ist, da wahrscheinlich das video device schon vom SIP Phone gebraucht wird. Jedenfalls werde ich mir das Thema nächste Woche näher anschauen, da ich für meine Produktiv Lösung zu Hause das Feature unbedingt benötige und ich mich mehr mit DoorPi Sourcecode auseinander setzen möchte..

Das bedeutet, dass ich neue Elemente in die Konfigurationsdatei einbauen werde:

[DoorPi]
snapshot_path = !Basepath!/doorpi/media/pictures --> Default
number_of_snapshots = 10 --> Default

[EVENT_OnSipPhoneMakeCallBefore] --> neues Event
10 = take_snapshot --> neue SingleAction

Im speziellen wird das video_device und video_size, wenn video_display_enabled, herangezogen um ein Bild bei EVENT_OnSipPhoneMakeCallBefore (ist neu, da sich ansonsten wahrscheinlich Überschneidungen beim video device ergeben) zu schießen. Gespeichert werden die
Bilder in einen sagen wir mal File Ringbuffer mit "number_of_snapshots" Größe. Durch die Datumseigenschaften der Bilder (jpg), kann dann Rückgeschlossen werden,
wann dieses Bild erstellt wurde. Eine einfache Bilderansicht mit neuem Reiter Snapshots im DoorPiWeb würde dann ausreichen.

Falls du weitere Anregungen zum Thema hast vor allem wegen Implementierung usw. gib bescheid.

**Comment by pmunz** [comment]
Hallo Thomas, plstreamer,
Freut mich sehr das dass DoorPi Projekt schon so weit vortgeschritten ist :) , ich hatte leider jetzt lange keine Zeit mehr mich darum zu kümmern hab aber jetzt wieder Zeit gefunden und das freut mich sehr.
@pistreamer eine Video oder Bild Aufzeichnung wäre auch für mich ein sehr Hilfreiches und nützliches 
Feature , vielleicht könnte man das ja wie du verschlägst realisieren.

[EVENT_OnSipPhoneMakeCallBefore] --> neues Event
10 = take_snapshot --> neue SingleAction

**Comment by pistreamer** [comment]
Hallo, Thomas...

habe das Feature soweit mal implementiert und bin gerade bei der Weboberfläche bzw. Anzeige von den Snapshots. Irgendwie habe ich vergessen, dass snapshot_path nicht über DoorPiWeb ansprechbar ist und somit die Images nicht dargestellt werden. Was meinst du sollten wir einen fixen Ordner im DoorPiWeb erstellen /dashboard/dist/snapshots oder hast du vl. eine andere Lösung.

Danke..

@pmunz: Ich denke das wäre möglich, wenn wir in der mail Action noch eine Variable einbauen.. zB
10 = mailto:motom001@gmail.com, Irgendeintext.... !snapshot!

sg chris

**Comment by pistreamer** [comment]
Erste Version ist in meinem Fork... gespeichert werden die Bilder zurzeit in !BASEPATH!/../DoorPiWeb/snapshots/
Pfad und getriggert über Aktion take_snapshot.
Im Webinterface habe ich ein neues Navigationselement unter History angelegt wo man die Snapshots ansehen kann.

**Comment by pistreamer** [comment]
@pmunz: mailto wurde nun erweitert um snapshot Funktion, ich muss es noch ausgiebig testen, bei mir jedenfalls haut es ohne Probleme hin.
Also wer Zeit und lust hat kann die neuen Funktionalitäten (Snapshot und mailto) von meinem Fork testen und vl. werden sie dann in den Master übernommen
.
MailTo Beispiel:

10 = mailto:teset@gmail.com, DoorPi, Someone is ringing!, True

--> True bedeutet dass ein Snapshot von Video device gemacht wird und als Attachment bei der Email hinzugefügt wird.

**Comment by motom001** [comment]
#101 
https://github.com/motom001/DoorPi/commit/10f28aba78b6cfc5e7a16aca0e2dbf07ffda7b5a

Kann an der Stelle geschlossen werden?

**Comment by pistreamer** [comment]
Von meiner Seite aus schon!
