### ISSUE TITLE
some questions from beginner

### ISSUE THREAD

**Issue by brunh** [motom001/DoorPi#99]
Hi, 
i have started to install doorpi in according to instruction from link: https://github.com/motom001/DoorPi/wiki/Installation
it seems to me i  made all steps, but now i have next questions ( sorry, maybe they are too simple , but i am beginner and i want to install it) :
1. when i finished all steps from this page, what should be next step?
2. i couldn't find out file doorpi.cfg ... shall i make the file by myself and put to the directory? 
3. it is not clear to me how  my raspberry should to react on pressing of push-button or RFID triggering, how can i understand that i set it right way? 

Sorry, i understand that you are replying a lot, but some your explanations in German are not clear completely to me... e.g. https://github.com/motom001/DoorPi/issues/95 after using google translator i couldn't understand  most of text...

p.s. i am very interesting in this your project and i will be so glad to be part of it by suggesting all my possible help,  for example  with some translations of texts of forum ( wiki)  into Russian :)

**Comment by Schwa-l-be** [comment]
welcome to the project. we try to translate all steps and make it as clear as possible, but i needs a lot of time. Some questions are already answered in german but i try to help you.
1.+2. You have to make a droopi.cfg (here are the parameters: https://github.com/motom001/DoorPi/wiki/doorpi.cfg). the configuration is at the moment available in german, but i do my best to translate it as soon as possible.
3. DoorPi needs Inputs and Outputs to be configured. They are called "keyboard", we try to change the name. 
You use InputPins to make a call or something else
and outputs pins to make something happen, like open the door through a relays

#95 is mostly for us to decide how to call the directory and how to make it more easy to the users to setup droopi with its config

if you have any further questions feel free to ask

**Comment by brunh** [comment]
Many thanks for your prompt reply! you're the best :) so now i will continue my work on it, and i'll back as soon as i will have next questions...

**Comment by motom001** [comment]
close?
